(()=>{
fetch('loader_v9.js',{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error('loader_v9.js: '+r.status);return r.text()}).then(t=>{
  const needle="function post(a,b,n){if(!s.includes(a)){console.warn('v9 patch skip:',n);return}s=s.replace(a,b)}\n";
  const inject=String.raw`
post("function treeRank(id,zone=Z()){return Math.max(0,Math.min(5,Number(zone.tree[id])||0))}","function areaBranches(id=M.area){return id==='qingyun'?['eco']:id==='blackwind'?['eco','fate']:['eco','res','fate']}function nodeBranch(id){return id.startsWith('eco')?'eco':id.startsWith('res')?'res':'fate'}function treeAllowedNode(id,area=M.area){return areaBranches(area).includes(nodeBranch(id))}function treeRank(id,zone=Z()){if(zone===Z()&&!treeAllowedNode(id,M.area))return 0;return Math.max(0,Math.min(5,Number(zone.tree[id])||0))}","area-specific branches");
post("function treeCount(id=M.area){return Object.values(M.zones[id].tree||{}).filter(v=>Number(v)>0).length}","function treeCount(id=M.area){let tr=M.zones[id].tree||{};return Object.entries(tr).filter(([k,v])=>treeAllowedNode(k,id)&&Number(v)>0).length}","area tree count");
post("function treeLevels(id=M.area){return Object.values(M.zones[id].tree||{}).reduce((a,v)=>a+Math.max(0,Math.min(5,Number(v)||0)),0)}","function treeLevels(id=M.area){let tr=M.zones[id].tree||{};return Object.entries(tr).reduce((a,[k,v])=>a+(treeAllowedNode(k,id)?Math.max(0,Math.min(5,Number(v)||0)):0),0)}","area tree levels");
post("function nodeReady(n){let q=nodeReq(n);return treeRank(n.id)<5&&meetsRealm(q)&&(!n.p||treeRank(n.p)>=3)}","function nodeReady(n){let q=nodeReq(n);return treeAllowedNode(n.id)&&treeRank(n.id)<5&&meetsRealm(q)&&(!n.p||treeRank(n.p)>=3)}","area node ready");
post("function renderTree(){u.tree.innerHTML='';const heads={eco:['생태','🩸'],res:['자원','⛏️'],fate:['인물·기연','✦']};","function renderTree(){u.tree.innerHTML='';let abs=areaBranches();u.tree.style.gridTemplateColumns='repeat('+abs.length+',1fr)';const heads={eco:['생태','🩸'],res:['자원','⛏️'],fate:['인물·기연','✦']};","area tree layout");
post("for(const key of ['eco','res','fate']){let br=document.createElement('div');","for(const key of ['eco','res','fate']){if(!areaBranches().includes(key))continue;let br=document.createElement('div');","hide unavailable branches");
post("u.nc.textContent=`${treeCount()} / 9 · 강화 ${treeLevels()} / 45`;u.treeHint.textContent=isMortal()?'수선에 입문하면 인연 트리가 열립니다.':'각 노드 최대 5단계 · 이전 노드 3/5부터 다음 단계 개방'","{let mb=areaBranches().length*3,ml=mb*5;u.nc.textContent=treeCount()+' / '+mb+' · 강화 '+treeLevels()+' / '+ml;let areaMsg=M.area==='qingyun'?'청운산: 요수 생태만 개척':M.area==='blackwind'?'흑풍곡: 요수 + 산수/탐보서 개척':'적혈비경: 요수 + 산수 + 영맥/정예 개척';u.treeHint.textContent=isMortal()?'수선에 입문하면 인연 트리가 열립니다.':areaMsg+' · 각 노드 3/5부터 다음 단계 개방'}","dynamic tree totals");
post("function unlockNode(id){if(ph==='run')return;let n=nodeBy(id);if(!n)return;","function unlockNode(id){if(ph==='run')return;let n=nodeBy(id);if(!n)return;if(!treeAllowedNode(id)){u.notice.textContent='이 비경에서는 해당 인연이 존재하지 않습니다.';return}","block unavailable nodes");
`;
  if(!t.includes(needle))throw new Error('v10 injection marker missing');
  t=t.replace(needle,needle+inject);
  (0,eval)(t);
}).catch(e=>{console.error(e);document.body.insertAdjacentHTML('beforeend','<pre style="position:fixed;inset:8px;z-index:9999;background:#200;color:#fcc;padding:12px;overflow:auto">게임 로드 실패: '+String(e)+'</pre>')});
})();