(()=>{
const parts=['game_part1.txt','game_part2.txt','game_part3.txt','game_part4.txt'];
function rep(s,a,b,n){if(!s.includes(a))throw new Error('v8 patch miss: '+n);return s.replace(a,b)}
Promise.all(parts.map(p=>fetch(p,{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error(`${p}: ${r.status}`);return r.text()}))).then(xs=>{
let s=xs.join('');
s=rep(s,"fresh=()=>({stone:0,herb:0,realm:","fresh=()=>({stone:0,herb:0,herb2:0,herb3:0,realm:","fresh herbs");
s=rep(s,"}}catch(e){} for(const a of AREAS){","}}catch(e){} M.herb=Number(M.herb)||0;M.herb2=Number(M.herb2)||0;M.herb3=Number(M.herb3)||0; for(const a of AREAS){","migrate herbs");
s=rep(s,"function areaIndex(id=M.area){return AREAS.findIndex(a=>a.id===id)}function meetsRealm","function areaIndex(id=M.area){return AREAS.findIndex(a=>a.id===id)}const HN=['하급','중급','상급'];function herbKey(g){return g<=0?'herb':g===1?'herb2':'herb3'}function herbHave(g){return Number(M[herbKey(g)])||0}function herbSpend(g,n){let k=herbKey(g);M[k]=(Number(M[k])||0)-n}function herbAdd(g,n){let k=herbKey(g);M[k]=(Number(M[k])||0)+n}function envPenalty(){return [{move:1,pick:1},{move:.90,pick:.82},{move:.80,pick:.68}][areaIndex()]||{move:.76,pick:.62}}function meetsRealm","helpers");
s=rep(s,"function nodeCost(n){let sc=[1,3,8][areaIndex()]||1,rank=treeRank(n.id),grow=1+rank*.72;return{s:Math.ceil(n.c.s*sc*grow),h:Math.ceil(n.c.h*(1+areaIndex()*.7)*grow)}}","function nodeCost(n){let sc=[1,3,8][areaIndex()]||1,rank=treeRank(n.id),grow=1+rank*.72;return{s:Math.ceil(n.c.s*sc*grow),h:Math.ceil(n.c.h*(1+areaIndex()*.7)*grow),hg:areaIndex()}}","node grade");
s=rep(s,"function trainCost(k){let lv=M.cult[k],base={atk:24,mov:28,sen:5,hp:7}[k],majorMul=1+Math.max(0,M.realm.major)*4;if(k==='sen'||k==='hp')return{h:Math.ceil(base*1.85**(lv-1)*(1+Math.max(0,M.realm.major)*1.4)),s:0};return{s:Math.ceil(base*2.2**(lv-1)*majorMul),h:0}}","function trainCost(k){let lv=M.cult[k],base={atk:24,mov:28,sen:5,hp:7}[k],majorMul=1+Math.max(0,M.realm.major)*4;if(k==='sen'||k==='hp')return{h:Math.ceil(base*1.85**(lv-1)*(1+Math.max(0,M.realm.major)*1.4)),s:0,hg:Math.min(2,Math.floor(lv/3))};return{s:Math.ceil(base*2.2**(lv-1)*majorMul),h:0,hg:0}}","train grade");
s=rep(s,"function breakthroughCost(){if(isMortal())return{s:0,h:8,init:true,major:false};let m=M.realm.major,s=M.realm.stage;if(s<9)return{s:Math.ceil(120*(1+m*5)*1.62**(s-1)),h:Math.ceil(18*(1+m*1.4)*1.28**(s-1)),major:false};return{s:Math.ceil(4800*(1+m*3.5)),h:Math.ceil(75*(1+m*1.8)),major:true}}","function breakthroughCost(){if(isMortal())return{s:0,h:8,hg:0,init:true,major:false};let m=M.realm.major,s=M.realm.stage;if(s<9)return{s:Math.ceil(120*(1+m*5)*1.62**(s-1)),h:Math.ceil(18*(1+m*1.4)*1.28**(s-1)),hg:Math.min(2,Math.floor(s/3)),major:false};return{s:Math.ceil(4800*(1+m*3.5)),h:Math.ceil(75*(1+m*1.8)),hg:2,major:true}}","break grade");
s=rep(s,"u.stone.textContent=M.stone;u.herb.textContent=M.herb;u.realm.textContent","u.stone.textContent=M.stone;u.herb.textContent=`下${M.herb} · 中${M.herb2} · 上${M.herb3}`;u.realm.textContent","herb hud");
s=rep(s,"u.desc.textContent=a.desc;if(isMortal())","{let ep=envPenalty();u.desc.textContent=`${a.desc} · 환경 이동 ${Math.round(ep.move*100)}% / 감응 ${Math.round(ep.pick*100)}%`}if(isMortal())","area env hud");
s=rep(s,"q.h?`${q.h} 영초`:`${q.s} 영석`","q.h?`${HN[q.hg]} 영초 ${q.h}`:`${q.s} 영석`","train text");
s=rep(s,"bt.init?`${bt.h} 영초 · 입문 즉시 전투/수련 개방`:`${bt.s} 영석 · ${bt.h} 영초${eventNeed?' · 축기 기연 필요':''}`","bt.init?`${HN[bt.hg]} 영초 ${bt.h} · 입문 즉시 전투/수련 개방`:`${bt.s} 영석 · ${HN[bt.hg]} 영초 ${bt.h}${eventNeed?' · 축기 기연 필요':''}`","break text");
s=rep(s,"`${q.s?`${q.s}석 `:''}${q.h?`${q.h}초`:''}`","`${q.s?`${q.s}석 `:''}${q.h?`${HN[q.hg]} ${q.h}초`:''}`","tree cost text");
s=rep(s,"if(M.stone<q.s||M.herb<q.h){u.notice.textContent='인연 강화 자원이 부족합니다.';return}M.stone-=q.s;M.herb-=q.h;Z().tree[id]=rank+1","if(M.stone<q.s||herbHave(q.hg)<q.h){u.notice.textContent=`인연 강화 자원이 부족합니다. ${q.h?HN[q.hg]+' 영초 필요':''}`;return}M.stone-=q.s;if(q.h)herbSpend(q.hg,q.h);Z().tree[id]=rank+1","tree spend");
s=rep(s,"function drop(type,x,y,val=1){O.push({type,x,y,r:type==='s'?7:8,val})}function rndDrop(){let p=pt();drop('h',p.x,p.y,1)}","function drop(type,x,y,val=1,grade=null){if(type==='h'&&grade==null){let ai=areaIndex();grade=ai===0?0:ai===1?(Math.random()<.78?1:0):(Math.random()<.72?2:1)}O.push({type,x,y,r:type==='s'?7:8,val,grade})}function rndDrop(){let p=pt();drop('h',p.x,p.y,1)}","herb drops");
s=rep(s,"let herbTotal=10+treeRank('res1')*2,herbInitial=Math.ceil(herbTotal*.78)","let herbTotal=10+areaIndex()*2+treeRank('res1')*2,herbInitial=Math.ceil(herbTotal*.78)","herb quantity");
s=rep(s,"R={s:0,h:0,left:0,buffs:{},elite:0,kills:0,beastKills:0,rivalKills:0,minHp:0,herbSpawnLeft","R={s:0,h:0,h0:0,h1:0,h2:0,left:0,buffs:{},elite:0,kills:0,beastKills:0,rivalKills:0,minHp:0,herbSpawnLeft","run herb grades");
s=rep(s,"M.stone+=q.s;M.herb+=q.h;return`<div class=\"event\"><b>기연 · ${q.t}</b>","M.stone+=q.s;if(q.h)herbAdd(areaIndex(),q.h);return`<div class=\"event\"><b>기연 · ${q.t}</b>","fortune herbs");
s=rep(s,"let ratio=reason==='return'?1:.4,s=Math.floor(R.s*ratio),h=Math.floor(R.h*ratio),event='';M.stone+=s;M.herb+=h;Z().runs++","let ratio=reason==='return'?1:.4,s=Math.floor(R.s*ratio),h=Math.floor(R.h*ratio),h0=Math.floor((R.h0||0)*ratio),h1=Math.floor((R.h1||0)*ratio),h2=Math.floor((R.h2||0)*ratio),event='';M.stone+=s;M.herb+=h0;M.herb2+=h1;M.herb3+=h2;Z().runs++","bank graded herbs");
s=rep(s,"<b>영석 ${s} · 영초 ${h}</b>","<b>영석 ${s} · 영초 下${h0} 中${h1} 上${h2}</b>","settle text");
s=rep(s,"function gainHerb(v,x=P.x,y=P.y,show=true){let n=Math.max(1,Math.floor(v));R.h+=n;if(show)pop(x,y,`+${n} 영초`,'#83e39b');return n}","function gainHerb(v,x=P.x,y=P.y,show=true,grade=areaIndex()){grade=Math.max(0,Math.min(2,grade??areaIndex()));let n=Math.max(1,Math.floor(v));R.h+=n;R['h'+grade]=(R['h'+grade]||0)+n;if(show)pop(x,y,`+${n} ${HN[grade]} 영초`,['#83e39b','#74d8b8','#b99cff'][grade]);return n}","gain graded herb");
s=rep(s,"let psp=(isMortal()?122:110+(M.cult.mov-1)*17)*Math.pow(Math.max(.7,realmPower()),.16)*(R.buffs.wind?1.22:1);","let psp=(isMortal()?122:110+(M.cult.mov-1)*17)*Math.pow(Math.max(.7,realmPower()),.16)*(R.buffs.wind?1.22:1)*envPenalty().move;","move penalty");
s=rep(s,"let pick=22+(M.cult.sen-1)*8+(R.buffs.gather?8:0);","let pick=(22+(M.cult.sen-1)*8+(R.buffs.gather?8:0))*envPenalty().pick;","pickup penalty");
s=rep(s,"else gainHerb(o.val,o.x,o.y);","else gainHerb(o.val,o.x,o.y,true,o.grade);","pickup grade");
s=rep(s,"u.loot.textContent=`영석 ${R.s} · 영초 ${R.h}${buffs}`","u.loot.textContent=`영석 ${R.s} · 영초 下${R.h0||0} 中${R.h1||0} 上${R.h2||0}${buffs}`","run loot text");
s=rep(s,"else C(o.x,o.y,o.r,'#46b469')","else C(o.x,o.y,o.r,['#46b469','#42a99a','#8e68d6'][o.grade||0])","herb colors");
s=rep(s,"g.arc(P.x,P.y,22+(M.cult.sen-1)*8,0,6.29)","g.arc(P.x,P.y,(22+(M.cult.sen-1)*8)*envPenalty().pick,0,6.29)","sense circle");
s=rep(s,"u.skill.onclick=()=>{if(ph!=='run'||scd||isMortal())return;let wave=M.skill==='wave',rad=wave?170:125,base=wave?6.2:10,inc=wave?2.5:4.2;scd=wave?3.8:5;burst=.22;burstR=rad;let h=0;for(const a of E)if(host(a)&&D(P,a)<rad){a.hp-=(base+(M.cult.atk-1)*inc)*realmPower()*(R.buffs.blade?1.25:1);h++}u.notice.textContent=h?`${h}개체에게 ${wave?'검풍':'어검술'} 적중.`:'주변에 공격할 대상이 없습니다.'};","u.skill.onclick=()=>{if(ph!=='run'||scd||isMortal())return;let wave=M.skill==='wave';if(wave){let rad=190,dmg=(6.8+(M.cult.atk-1)*2.7)*realmPower()*(R.buffs.blade?1.25:1),h=0;scd=3.8;burst=.24;burstR=rad;for(const a of E){if(!host(a)||D(P,a)>=rad)continue;a.hp-=dmg;let dx=a.x-P.x,dy=a.y-P.y,q=Math.hypot(dx,dy)||1;a.x=cl(a.x+dx/q*18,16,684);a.y=cl(a.y+dy/q*18,16,444);pop(a.x,a.y,'-'+Math.round(dmg),'#9fdfff',.55);h++}u.notice.textContent=h?'검풍으로 '+h+'개체 동시 타격.':'검풍 범위 안에 적이 없습니다.'}else{let target=null,dd=1e9;for(const a of E){if(!host(a))continue;let d=D(P,a);if(d<150&&d<dd){dd=d;target=a}}scd=5;burst=.2;burstR=125;if(target){let dmg=(13+(M.cult.atk-1)*5.1)*realmPower()*(R.buffs.blade?1.25:1);target.hp-=dmg;pop(target.x,target.y,'-'+Math.round(dmg),'#eeeeee',.55);u.notice.textContent='어검술 집중 타격.'}else u.notice.textContent='어검술 사거리 안에 적이 없습니다.'}};","skill behavior");
s=rep(s,"if(q.h){if(M.herb<q.h)return u.notice.textContent='영초가 부족합니다.';M.herb-=q.h}else","if(q.h){if(herbHave(q.hg)<q.h)return u.notice.textContent=`${HN[q.hg]} 영초가 부족합니다.`;herbSpend(q.hg,q.h)}else","train spend");
s=rep(s,"if(M.stone<q.s||M.herb<q.h){u.notice.textContent=q.init?'입문 자원이 부족합니다. 한두 번 더 안전하게 비경을 다녀오세요.':'경지 돌파 자원이 부족합니다.';return}M.stone-=q.s;M.herb-=q.h;","if(M.stone<q.s||herbHave(q.hg)<q.h){u.notice.textContent=q.init?'하급 영초가 부족합니다. 한두 번 더 안전하게 비경을 다녀오세요.':`${HN[q.hg]} 영초 또는 영석이 부족합니다.`;return}M.stone-=q.s;if(q.h)herbSpend(q.hg,q.h);","break spend");
(0,eval)(s)
}).catch(e=>{console.error(e);document.body.insertAdjacentHTML('beforeend','<pre style="position:fixed;inset:8px;z-index:9999;background:#200;color:#fcc;padding:12px;overflow:auto">게임 로드 실패: '+String(e)+'</pre>')})
})();