(()=>{
'use strict';
const D=window.__xianxiaDebug,P=window.__xianxiaProgression;if(!D||!P||window.__xianxiaUiVersion==='11.13')return;window.__xianxiaUiVersion='11.13';
const $=s=>document.querySelector(s), C=D.constants, H=['하급','중급','상급'];
const AG={qingyun:'青',blackwind:'風',blood:'血',thunder:'雷'}, SG={sword:'刃',wave:'風',chain:'連',thunder:'雷',array:'陣'};
const POS={sword:[12,59],wave:[28,31],chain:[50,14],thunder:[72,31],array:[88,59]}, RESULT=new Set(['무사 귀환','육신 중상','비경 붕괴']);
let sel={t:'heart'};
const snap=()=>D.snapshot(), M=()=>snap().M, hk=g=>g===0?'herb':g===1?'herb2':'herb3', have=(m,g)=>+m[hk(g)]||0;
const reached=(m,r)=>m.realm?.major>=0&&(m.realm.major>r.major||(m.realm.major===r.major&&m.realm.stage>=r.stage));
const sk=id=>C.SKILLS.find(x=>x.id===id), ss=(m,id)=>(m.skills[id]||={u:0,pow:0,range:0,cycle:0});
const cap=(m,s)=>!reached(m,s.req)?0:m.realm.major>s.req.major?5:Math.max(1,Math.min(5,m.realm.stage-s.req.stage+1));
const cost=(s,k,n)=>{const t=C.SKILLS.indexOf(s)+1;return{s:Math.ceil((18+t*18)*1.58**(n-1)),h:k==='cycle'?Math.ceil((t+n)/2):0,hg:s.grade}};
function css(){if($('#v1113style'))return;let s=document.createElement('style');s.id='v1113style';s.textContent=`
.v1113-hide{display:none!important}#ascViewport,#mapViewport,#skillTreeViewport{position:relative}
#ascDetail.v13float,#mapDetail.v13float,#skillDetail.v13float{position:absolute;z-index:60;width:min(235px,calc(100% - 14px));max-height:195px;overflow:auto;margin:0!important;padding:8px!important;border:1px solid #58706d!important;border-radius:10px;background:#09161bdd;box-shadow:0 14px 34px #000c;backdrop-filter:blur(9px);display:none;pointer-events:auto}#ascDetail.v13float.open,#mapDetail.v13float.open,#skillDetail.v13float.open{display:block}.v13float p{font-size:8.5px!important;line-height:1.3!important;margin:4px 0!important}.v13float .detail-action{min-height:31px!important;margin-top:5px!important;font-size:9px!important}.v13close{position:absolute;right:4px;top:4px;width:21px;height:21px;margin:0;padding:0;border:1px solid #52666a;border-radius:50%;background:#142126;font-size:11px}
.skill13{margin:0}.skill13head{display:flex;justify-content:space-between;gap:8px;margin-bottom:6px}.skill13head b{font-size:13px}.skill13head span{font-size:9px;color:#8fa39e}.skill13view{position:relative;height:410px;overflow:hidden;border:1px solid #31474a;border-radius:12px;background:radial-gradient(circle at 50% 76%,#29234299,#101823 55%,#071014)}.skill13svg{position:absolute;inset:0;width:100%;height:100%;pointer-events:none}.s13line{stroke:#525875;stroke-width:2.2;fill:none;opacity:.55}.s13line.on{stroke:#9b89d3;opacity:.95}.s13line.ready{stroke:#c2a856;stroke-dasharray:7 5}.s13node{position:absolute;transform:translate(-50%,-50%);margin:0;border:1px solid #4d5363;background:#141a27;color:#8d95a8;text-align:center;box-shadow:0 5px 14px #0008}.s13heart{left:50%;top:82%;width:76px;height:76px;border-radius:50%;border-color:#8576b0;background:#2b2340;color:#e5dcff}.s13heart b{font:700 13px serif}.s13main{width:60px;height:60px;border-radius:50%;padding:4px}.s13main b{display:block;font:800 19px serif}.s13main small{font-size:7px}.s13main.on{border-color:#9b8bd5;background:#292443;color:#eee7ff}.s13main.ready{border-color:#c5a957;color:#f4dfa0;box-shadow:0 0 16px #d7b95a44}.s13main.locked{opacity:.4}.s13up{width:45px;height:38px;border-radius:9px;padding:2px;font-size:8px}.s13up.on{border-color:#796db0;background:#211d37}.s13up.ready{border-color:#c5a957;color:#f4dfa0}.s13up.done{border-color:#5fae92;background:#17372f;color:#d4f3e8}.s13up.locked{opacity:.38}
.dialog.v13result{position:relative;max-height:94%!important;overflow:hidden!important;padding:7px 9px!important}.dialog.v13result h3{font-size:17px!important;margin:0 0 2px!important}.dialog.v13result .intro{margin:2px 0 3px!important;font-size:8px!important}.dialog.v13result #ox{font-size:9px!important;line-height:1.25!important;margin:2px 0!important}.dialog.v13result #ox>b{display:block;font-size:11px;margin:2px}.dialog.v13result #ox .event{margin:3px 0!important;padding:4px 6px!important;font-size:7.5px!important;line-height:1.2!important}.dialog.v13result #expeditionAreaPicker,.dialog.v13result .expedition-plan-label,.dialog.v13result #planChoices{display:none!important}.v13quick{display:flex;gap:4px;margin:4px 0}.v13chip{flex:1;padding:5px;border:1px solid #354b50;border-radius:8px;background:#101c21;font-size:8px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.v13actions{display:grid;grid-template-columns:1fr .8fr;gap:4px}.v13actions #start{margin:0!important;min-height:33px!important;font-size:9px!important}.v13settings{margin:0;border:1px solid #42575c;border-radius:8px;background:#16262b;font-size:8px}.v13back{position:absolute;z-index:90;inset:0;background:#020608bf;display:none}.v13back.open{display:block}.v13sheet{position:absolute;left:6px;right:6px;bottom:6px;padding:8px;border:1px solid #4c6467;border-radius:11px;background:#0c181df8}.v13sheet h4{margin:0 0 6px;font-size:11px}.v13label{font-size:8px;color:#829792;margin:5px 0 3px}.v13areas{display:grid;grid-template-columns:repeat(4,1fr);gap:3px}.v13plans{display:grid;grid-template-columns:repeat(3,1fr);gap:3px}.v13areas button,.v13plans button{margin:0;min-height:36px;padding:3px 2px;border:1px solid #354b50;border-radius:7px;background:#132228;font-size:7px}.v13areas button.on,.v13plans button.on{border-color:#c5aa5a;background:#332d1d;color:#f7e4a8}.v13done{width:100%;min-height:29px;margin:6px 0 0;border:1px solid #4f7b6e;border-radius:7px;background:#1e4d41;font-size:8px}
@media(max-width:560px){.skill13view{height:390px}#ascDetail.v13float,#mapDetail.v13float,#skillDetail.v13float{width:min(215px,calc(100% - 12px));max-height:180px}}
`;document.head.appendChild(s)}
function closeBtn(d){if(d.querySelector('.v13close'))return;let b=document.createElement('button');b.className='v13close';b.textContent='×';b.onclick=e=>{e.stopPropagation();d.classList.remove('open')};d.appendChild(b)}
function place(v,n,d){d.classList.add('open');closeBtn(d);d.style.visibility='hidden';requestAnimationFrame(()=>{let a=v.getBoundingClientRect(),b=n.getBoundingClientRect(),w=d.offsetWidth||220,h=d.offsetHeight||130,x=b.right-a.left+7;if(x+w>a.width-7)x=b.left-a.left-w-7;if(x<7)x=Math.max(7,(a.width-w)/2);let y=b.top-a.top+b.height/2-h/2;y=Math.max(7,Math.min(a.height-h-7,y));d.style.left=x+'px';d.style.top=y+'px';d.style.visibility='visible'})}
function floatify(vs,ds,ns,key){let v=$(vs),d=$(ds);if(!v||!d||window[key])return;window[key]=1;d.classList.add('v13float');v.appendChild(d);d.classList.remove('open');v.addEventListener('click',e=>{let n=e.target.closest(ns);if(n){requestAnimationFrame(()=>place(v,n,d));return}if(!e.target.closest(ds))d.classList.remove('open')},true);['pointerdown','pointermove','pointerup','click'].forEach(t=>d.addEventListener(t,e=>e.stopPropagation()))}
function floating(){floatify('#ascViewport','#ascDetail','.asc-node','__v13a');floatify('#mapViewport','#mapDetail','.map-node','__v13m');let r=$('[data-panel="train"] .record-grid')?.closest('.section');if(r)r.classList.add('v1113-hide')}
function line(svg,a,b,cls){let p=document.createElementNS('http://www.w3.org/2000/svg','line');p.setAttribute('x1',a[0]+'%');p.setAttribute('y1',a[1]+'%');p.setAttribute('x2',b[0]+'%');p.setAttribute('y2',b[1]+'%');p.setAttribute('class','s13line '+cls);svg.appendChild(p)}
function node(w,x,y,cls,html,fn){let b=document.createElement('button');b.className='s13node '+cls;b.style.left=x+'%';b.style.top=y+'%';b.innerHTML=html;b.onclick=e=>{e.stopPropagation();fn()};w.appendChild(b);return b}
function setupSkills(){let p=$('[data-panel="skills"]');if(!p)return;p.innerHTML='<div class="section skill13"><div class="skill13head"><b>법술 · 검맥도</b><span>검심에서 각 법술 계통으로 분기</span></div><div id="skillTreeViewport" class="skill13view"><svg id="skill13svg" class="skill13svg"></svg><div id="skill13world"></div><div id="skillDetail" class="detail v13float"></div></div></div>';floatify('#skillTreeViewport','#skillDetail','.s13node','__v13s');$('.tab-btn[data-tab="skills"]')?.addEventListener('click',renderSkills);renderSkills()}
function ups(pos){let dx=pos[0]-50,dy=pos[1]-82,l=Math.hypot(dx,dy)||1,ux=dx/l,uy=dy/l,px=-uy,py=ux,b=[pos[0]+ux*16,pos[1]+uy*16];return[-1,0,1].map(k=>[b[0]+px*k*8,b[1]+py*k*8])}
function renderSkills(){let w=$('#skill13world'),svg=$('#skill13svg');if(!w||!svg)return;w.replaceChildren();svg.innerHTML='';let m=M(),ph=snap().phase,heart=[50,82];node(w,50,82,'s13heart','<b>心 · 검심</b>',()=>{sel={t:'heart'};detail()});for(let s of C.SKILLS){let p=POS[s.id],st=ss(m,s.id),open=reached(m,s.req),un=open&&!st.u&&ph!=='run'&&m.stone>=s.unlock.s&&have(m,s.grade)>=s.unlock.h;line(svg,heart,p,st.u?'on':un?'ready':'');node(w,p[0],p[1],'s13main '+(st.u?'on':un?'ready':'locked'),`<b>${SG[s.id]}</b><small>${s.n}</small>`,()=>{sel={t:'skill',id:s.id};detail()});let ps=ups(p),keys=['pow','range','cycle'],nm=['위력',s.id==='chain'?'타수':'범위','순환'];keys.forEach((k,i)=>{let cp=cap(m,s),lv=+st[k]||0,c=cost(s,k,lv+1),can=st.u&&lv<cp&&ph!=='run'&&m.stone>=c.s&&have(m,c.hg)>=c.h,cl=lv>=cp&&cp?'done':can?'ready':st.u?'on':'locked';line(svg,p,ps[i],st.u?'on':'');node(w,ps[i][0],ps[i][1],'s13up '+cl,`${nm[i]}<br><small>${lv}/${cp}</small>`,()=>{sel={t:'up',id:s.id,k};detail()})})}detail()}
function unlock(id){let m=M(),s=sk(id),st=ss(m,id);if(st.u||!reached(m,s.req)||snap().phase==='run')return;if(m.stone<s.unlock.s||have(m,s.grade)<s.unlock.h)return;m.stone-=s.unlock.s;m[hk(s.grade)]-=s.unlock.h;st.u=1;D.replaceState(m);renderSkills()}
function up(id,k){let m=M(),s=sk(id),st=ss(m,id),cp=cap(m,s),lv=+st[k]||0;if(!st.u||lv>=cp||snap().phase==='run')return;let c=cost(s,k,lv+1);if(m.stone<c.s||have(m,c.hg)<c.h)return;m.stone-=c.s;if(c.h)m[hk(c.hg)]-=c.h;st[k]=lv+1;D.replaceState(m);renderSkills()}
function detail(){let d=$('#skillDetail'),m=M();if(!d)return;if(sel.t==='heart'){d.innerHTML='<div class="detail-head"><b>心 · 검심</b><span>법술 본원</span></div><p>전승한 법술은 모두 자동 발동합니다. 각 계통에서 위력·범위/타수·순환을 따로 강화합니다.</p>';return}let s=sk(sel.id),st=ss(m,s.id);if(sel.t==='skill'){let open=reached(m,s.req),can=open&&!st.u&&snap().phase!=='run'&&m.stone>=s.unlock.s&&have(m,s.grade)>=s.unlock.h;d.innerHTML=`<div class="detail-head"><b>${SG[s.id]} ${s.n}</b><span>${st.u?'전승 완료':open?'전승 가능':'잠김'}</span></div><p>${s.desc}</p><div>${st.u?'✓ 자동 발동':open?`영석 ${s.unlock.s} · ${H[s.grade]} 영초 ${s.unlock.h}`:`경지 조건 미달`}</div>`;if(!st.u){let b=document.createElement('button');b.className='detail-action '+(can?'ready':'');b.disabled=!can;b.textContent='법술 전승';b.onclick=()=>unlock(s.id);d.appendChild(b)}return}let cp=cap(m,s),lv=+st[sel.k]||0,c=cost(s,sel.k,lv+1),can=st.u&&lv<cp&&snap().phase!=='run'&&m.stone>=c.s&&have(m,c.hg)>=c.h,n={pow:'위력',range:'범위·타수',cycle:'순환'}[sel.k];d.innerHTML=`<div class="detail-head"><b>${s.n} · ${n}</b><span>${lv}/${cp}</span></div><p>${sel.k==='pow'?'피해량 증가':sel.k==='range'?'범위 또는 연쇄 타수 증가':'자동 발동 주기 단축'}</p><div>${!st.u?'법술 전승 필요':lv>=cp?'현재 경지 상한':`다음 강화 · 영석 ${c.s}${c.h?` · ${H[c.hg]} 영초 ${c.h}`:''}`}</div>`;let b=document.createElement('button');b.className='detail-action '+(can?'ready':'');b.disabled=!can;b.textContent=lv>=cp?'현재 경지 상한':`${n} 강화`;b.onclick=()=>up(s.id,sel.k);d.appendChild(b)}
function plan(){let m=M();return C.PLANS.find(x=>x.id===m.settings?.plan)||C.PLANS[0]}
function resultUI(){let t=$('#ot'),dlg=t?.closest('.dialog'),start=$('#start');if(!dlg||!start)return;let result=RESULT.has(t.textContent.trim());dlg.classList.toggle('v13result',result);if(!result){let q=$('#v13quick'),a=$('#v13actions');q?.classList.add('v1113-hide');$('#v13back')?.classList.remove('open');if(a&&start.parentElement===a){a.parentNode.insertBefore(start,a);a.classList.add('v1113-hide')}return}let q=$('#v13quick');if(!q){q=document.createElement('div');q.id='v13quick';q.className='v13quick';start.parentNode.insertBefore(q,start)}let a=$('#v13actions');if(!a){a=document.createElement('div');a.id='v13actions';a.className='v13actions';start.parentNode.insertBefore(a,start);a.appendChild(start);let c=document.createElement('button');c.id='v13settings';c.className='v13settings';c.textContent='원정 설정 변경';a.appendChild(c)}let back=$('#v13back');if(!back){back=document.createElement('div');back.id='v13back';back.className='v13back';back.innerHTML='<div class="v13sheet"><h4>원정 설정</h4><div class="v13label">비경</div><div id="v13areas" class="v13areas"></div><div class="v13label">탐색 방법</div><div id="v13plans" class="v13plans"></div><button id="v13done" class="v13done">이 설정으로 준비</button></div>';dlg.appendChild(back);back.onclick=e=>{if(e.target===back)back.classList.remove('open')};$('#v13done').onclick=()=>back.classList.remove('open')}q.classList.remove('v1113-hide');$('#v13actions')?.classList.remove('v1113-hide');$('#v13settings').onclick=()=>{sheet();back.classList.add('open')};start.textContent='같은 설정으로 다시 진입';summary()}
function summary(){let q=$('#v13quick');if(!q)return;let m=M(),a=C.AREAS.find(x=>x.id===m.area),p=plan();q.innerHTML=`<div class="v13chip">비경 · <b>${AG[m.area]} ${a?.name.replace(' 후산','')}</b></div><div class="v13chip">방침 · <b>${p.icon} ${p.name}</b></div>`}
function sheet(){let m=M(),ag=$('#v13areas'),pg=$('#v13plans');if(!ag||!pg)return;ag.replaceChildren();C.AREAS.filter(a=>m.unlocked?.[a.id]).forEach(a=>{let b=document.createElement('button');b.className=m.area===a.id?'on':'';b.innerHTML=`<b>${AG[a.id]}</b>${a.name.replace(' 후산','')}`;b.onclick=()=>{D.selectArea(a.id);sheet();summary()};ag.appendChild(b)});pg.replaceChildren();C.PLANS.forEach(p=>{let b=document.createElement('button');b.className=m.settings?.plan===p.id?'on':'';b.textContent=`${p.icon} ${p.name}`;b.onclick=()=>{D.selectPlan(p.id);sheet();summary()};pg.appendChild(b)})}
function bindResult(){let t=$('#ot'),ov=$('#ov');if(t)new MutationObserver(resultUI).observe(t,{childList:true,subtree:true,characterData:true});if(ov)new MutationObserver(resultUI).observe(ov,{attributes:true,attributeFilter:['class']});resultUI()}
function boot(){css();floating();setupSkills();bindResult();setTimeout(()=>{floating();resultUI()},150)}boot();
})();