(()=>{
'use strict';
if(window.__xianxiaInkRuntime?.version==='11.31.1')return;
const W=700,H=460,EXIT={x:350,y:438},BASE='assets/ink_v1/';
const CACHE=new URL(document.currentScript?.src||location.href).searchParams.get('v')||'dev';
const files={
 player:'source/player_core.png',objects:'source/world_objects.png',effects:'source/skill_effects.png',
 qingyun_guard:'source/qingyun_stone_boar.png',qingyun_chaser:'source/qingyun_wind_wolf.png',
 blackwind_guard:'source/blackwind_horned_yak.png',blackwind_chaser:'source/blackwind_ink_panther.png',
 blood_guard:'source/blood_armored_bear.png',blood_chaser:'source/blood_ember_fox.png',
 thunder_guard:'source/thunder_stone_rhino.png',thunder_chaser:'source/thunder_lightning_leopard.png',
 bg_qingyun:'runtime/backgrounds/qingyun.png',bg_blackwind:'runtime/backgrounds/blackwind.png',
 bg_blood:'runtime/backgrounds/blood.png',bg_thunder:'runtime/backgrounds/thunder.png'
};
const S={version:'11.31.1',ready:false,error:null,images:{},layer:null,ctx:null};
window.__xianxiaInkRuntime=S;
const tracks=new Map(),deaths=[],casts=[],impacts=[],pickups=[],floaters=[];
let nextId=1,prevP=null,pFacing=1,prevCooldowns={},lastArea=null,lastPhase=null,prevObjects=[],prevRun=null,hitStopUntil=0,lastSnapshot=null;
const bounds=new Map(),refs=new Map();
function load(path){return new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>resolve(im);im.onerror=()=>reject(new Error('image failed: '+path));im.src=BASE+path+'?v='+encodeURIComponent(CACHE)})}
function makeLayer(){const game=document.querySelector('#game'),base=document.querySelector('#cv');if(!game||!base)return false;let c=document.querySelector('#v1131InkLayer');if(!c){c=document.createElement('canvas');c.id='v1131InkLayer';c.width=W;c.height=H;c.setAttribute('aria-hidden','true');base.insertAdjacentElement('afterend',c)}S.layer=c;S.ctx=c.getContext('2d');S.ctx.imageSmoothingEnabled=true;return true}
function frame(t,fps,count,offset=0){return Math.floor((t+offset)*fps)%count}
function progress(p,count){return Math.max(0,Math.min(count-1,Math.floor(Math.max(0,Math.min(.999,p))*count)))}
function median(values){const a=[...values].sort((x,y)=>x-y);return a.length?a[Math.floor(a.length/2)]:1}
function spansFor(data,img,y0,y1,cols){const spans=[];let start=-1,last=-1;for(let px=0;px<img.width;px++){let hits=0;for(let py=y0;py<y1;py++)if(data[(py*img.width+px)*4+3]>28)hits++;if(hits>2){if(start<0||px-last>8){if(start>=0)spans.push({l:start,r:last});start=px}last=px}}if(start>=0)spans.push({l:start,r:last});const minWidth=Math.max(12,Math.floor(img.width/cols*.18)),usable=spans.filter(s=>s.r-s.l+1>=minWidth);if(usable.length>=cols)return usable.sort((a,b)=>(b.r-b.l)-(a.r-a.l)).slice(0,cols).sort((a,b)=>a.l-b.l).map(s=>({l:Math.max(0,s.l-6),r:Math.min(img.width-1,s.r+6)}));return Array.from({length:cols},(_,i)=>({l:Math.floor(i*img.width/cols),r:Math.floor((i+1)*img.width/cols)-1}))}
function largestOpaqueBox(data,img,x0,x1,y0,y1){const w=x1-x0,h=y1-y0,seen=new Uint8Array(w*h),queue=new Int32Array(w*h);let best=null,bestSize=0;for(let sy=0;sy<h;sy++)for(let sx=0;sx<w;sx++){const seed=sy*w+sx;if(seen[seed]||data[((y0+sy)*img.width+x0+sx)*4+3]<=28)continue;let head=0,tail=1,size=0,l=sx,r=sx,t=sy,b=sy;queue[0]=seed;seen[seed]=1;while(head<tail){const at=queue[head++],px=at%w,py=(at/w)|0;size++;if(px<l)l=px;if(px>r)r=px;if(py<t)t=py;if(py>b)b=py;let n;if(px>0){n=at-1;if(!seen[n]&&data[((y0+py)*img.width+x0+px-1)*4+3]>28){seen[n]=1;queue[tail++]=n}}if(px<w-1){n=at+1;if(!seen[n]&&data[((y0+py)*img.width+x0+px+1)*4+3]>28){seen[n]=1;queue[tail++]=n}}if(py>0){n=at-w;if(!seen[n]&&data[((y0+py-1)*img.width+x0+px)*4+3]>28){seen[n]=1;queue[tail++]=n}}if(py<h-1){n=at+w;if(!seen[n]&&data[((y0+py+1)*img.width+x0+px)*4+3]>28){seen[n]=1;queue[tail++]=n}}}if(size>bestSize){bestSize=size;const pad=4,ll=Math.max(0,l-pad),rr=Math.min(w-1,r+pad),tt=Math.max(0,t-pad),bb=Math.min(h-1,b+pad);best={x:x0+ll,y:y0+tt,w:rr-ll+1,h:bb-tt+1}}}return best}
function prepare(key,counts){const img=S.images[key],rows=counts.length,c=document.createElement('canvas');c.width=img.width;c.height=img.height;const x=c.getContext('2d',{willReadFrequently:true});x.drawImage(img,0,0);const data=x.getImageData(0,0,c.width,c.height).data,body=[],beast=/_guard$|_chaser$/.test(key);counts.forEach((cols,row)=>{const rowHeights=[],y0=Math.floor(row*img.height/rows),y1=Math.floor((row+1)*img.height/rows),spans=spansFor(data,img,y0,y1,cols);for(let index=0;index<cols;index++){const pad=beast?32:0,x0=beast?Math.max(0,Math.floor(index*img.width/cols)-pad):spans[index].l,x1=beast?Math.min(img.width,Math.floor((index+1)*img.width/cols)+pad):spans[index].r+1,component=beast?largestOpaqueBox(data,img,x0,x1,y0,y1):null;let l=component?.x??x1,t=component?.y??y1,r=component?component.x+component.w-1:x0,b=component?component.y+component.h-1:y0;if(!component)for(let py=y0;py<y1;py++)for(let px=x0;px<x1;px++)if(data[(py*img.width+px)*4+3]>28){if(px<l)l=px;if(px>r)r=px;if(py<t)t=py;if(py>b)b=py}if(r<l||b<t){l=x0;r=x1-1;t=y0;b=y1-1}const box={x:l,y:t,w:r-l+1,h:b-t+1};bounds.set(`${key}:${row}:${cols}:${index}`,box);rowHeights.push(box.h);if(row<2)body.push(box.h)}refs.set(`${key}:${row}`,median(rowHeights))});refs.set(`${key}:body`,median(body))}
function boxFor(key,row,cols,index){return bounds.get(`${key}:${row}:${cols}:${index}`)}
function anchored(key,row,cols,index,x,groundY,targetHeight,flip=false,alpha=1,group='body',filter='none'){const img=S.images[key],b=boxFor(key,row,cols,index);if(!img||!b)return;const scale=targetHeight/(refs.get(`${key}:${group}`)||b.h),dw=b.w*scale,dh=b.h*scale,c=S.ctx;c.save();c.globalAlpha=alpha;c.filter=filter;c.translate(x,groundY);if(flip)c.scale(-1,1);c.drawImage(img,b.x,b.y,b.w,b.h,-dw/2,-dh,dw,dh);c.restore()}
function centered(key,row,cols,index,x,y,targetHeight,flip=false,alpha=1,filter='none'){const img=S.images[key],b=boxFor(key,row,cols,index);if(!img||!b)return;const scale=targetHeight/(refs.get(`${key}:${row}`)||b.h),dw=b.w*scale,dh=b.h*scale,c=S.ctx;c.save();c.globalAlpha=alpha;c.filter=filter;c.translate(x,y);if(flip)c.scale(-1,1);c.drawImage(img,b.x,b.y,b.w,b.h,-dw/2,-dh/2,dw,dh);c.restore()}
function shadow(x,y,w,h,a=.16){const c=S.ctx;c.save();c.globalAlpha=a;c.fillStyle='#1b2924';c.beginPath();c.ellipse(x,y,w,h,0,0,Math.PI*2);c.fill();c.restore()}
function drawPlayerSlash(x,groundY,p,flip){if(p<.16||p>.9)return;const q=Math.max(0,Math.min(1,(p-.16)/.74)),c=S.ctx;c.save();c.translate(x,groundY-29);if(flip)c.scale(-1,1);c.lineCap='round';c.globalAlpha=Math.sin(Math.PI*q)*.72;c.strokeStyle='rgba(41,65,71,.42)';c.lineWidth=8;c.beginPath();c.arc(-2,2,39,-2.42,-2.42+2.72*q);c.stroke();c.globalAlpha=Math.sin(Math.PI*q)*.92;c.strokeStyle='rgba(222,232,223,.9)';c.lineWidth=2.2;c.beginPath();c.arc(-2,2,40,-2.42,-2.42+2.72*q);c.stroke();c.restore()}
function dist(a,b){return Math.hypot((a?.x||0)-(b?.x||0),(a?.y||0)-(b?.y||0))}
function match(curr,now,area){const old=[...tracks.values()],used=new Set(),out=[];for(const e of curr){let best=null,bd=e.type==='rat'?45:80;for(const t of old){if(used.has(t.id)||t.type!==e.type)continue;const d=Math.hypot(e.x-t.x,e.y-t.y);if(d<bd){bd=d;best=t}}if(!best){best={id:nextId++,type:e.type,x:e.x,y:e.y,px:e.x,py:e.y,seen:now,facing:1,attackStart:-9,lastAttack:-9,area,maxHp:e.hp,lastHp:e.hp,hitUntil:0};tracks.set(best.id,best)}else used.add(best.id);best.px=best.x;best.py=best.y;best.x=e.x;best.y=e.y;best.e=e;best.seen=now;best.area=area;best.maxHp=Math.max(best.maxHp||e.hp,e.hp);if(e.hp<(best.lastHp??e.hp)-.05){const damage=(best.lastHp??e.hp)-e.hp;best.hitUntil=now+.12;impacts.push({x:e.x,y:e.y,damage,start:now,fromX:lastSnapshot?.P?.x??e.x,fromY:lastSnapshot?.P?.y??e.y});hitStopUntil=Math.max(hitStopUntil,now+.045)}best.lastHp=e.hp;const dx=best.x-best.px;if(Math.abs(dx)>.12)best.facing=dx<0?-1:1;out.push(best)}for(const t of [...tracks.values()]){if(out.includes(t))continue;if(now-t.seen<.22)deaths.push({...t,start:now});tracks.delete(t.id)}return out}
function drawBackground(area){const c=S.ctx,img=S.images['bg_'+area]||S.images.bg_qingyun;c.globalAlpha=1;c.drawImage(img,0,0,W,H);const wash=c.createLinearGradient(0,0,0,H);wash.addColorStop(0,'rgba(247,243,229,.08)');wash.addColorStop(1,'rgba(20,31,28,.10)');c.fillStyle=wash;c.fillRect(0,0,W,H)}
function drawPortal(t){shadow(EXIT.x,EXIT.y+2,32,6,.18);centered('objects',3,6,frame(t,7,6),EXIT.x,EXIT.y-12,74,false,.9)}
function drawObjects(s,t){for(const o of s.objects||[]){if(o.type==='h'){const row=Math.max(0,Math.min(2,o.grade||0)),ground=o.y+16;shadow(o.x,ground,9,2.5,.13);anchored('objects',row,4,frame(t,1.55,4,(o.x+o.y)*.0015),o.x,ground,40,false,.96,String(row))}else{const ground=o.y+14;shadow(o.x,ground,9,3,.15);anchored('objects',4,4,0,o.x,ground,34,false,1,'4')}}if(s.vein){const ground=s.vein.y+22;shadow(s.vein.x,ground,18,5,.2);anchored('objects',4,4,3,s.vein.x,ground,58,false,1,'4')}}
function drawHazards(s){const c=S.ctx;for(const h of s.hazards||[]){c.save();const p=h.struck?1:1-Math.max(0,h.t)/(h.ttl||1);c.globalAlpha=h.struck?.8:.25+p*.45;c.strokeStyle=h.struck?'#eaf4ff':'#495b82';c.lineWidth=h.struck?4:2;c.setLineDash(h.struck?[]:[6,6]);c.beginPath();c.arc(h.x,h.y,h.r*(.82+p*.18),0,Math.PI*2);c.stroke();if(h.struck){c.beginPath();c.moveTo(h.x-7,h.y-60);c.lineTo(h.x+5,h.y-24);c.lineTo(h.x-3,h.y-24);c.lineTo(h.x+9,h.y);c.stroke()}c.restore()}}
function enemyKey(area,type){if(type==='guard'||type==='elite')return area+'_guard';return area+'_chaser'}
function drawBar(x,y,w,ratio,elite=false){const c=S.ctx;c.save();c.fillStyle='rgba(32,29,24,.68)';c.fillRect(x-w/2,y,w,5);c.fillStyle=elite?'#9b3e34':'#d5cba7';c.fillRect(x-w/2+1,y+1,(w-2)*Math.max(0,Math.min(1,ratio)),3);c.strokeStyle='rgba(244,238,215,.82)';c.lineWidth=.7;c.strokeRect(x-w/2+.5,y+.5,w-1,4);c.restore()}
function drawEnemyMarker(x,y,h,elite=false,rare=false){const c=S.ctx;c.save();c.globalAlpha=.88;c.strokeStyle=rare?'#b78c45':elite?'#9b3e34':'rgba(244,238,215,.88)';c.lineWidth=elite?2.3:1.5;c.beginPath();c.ellipse(x,y+20,elite?31:25,elite?9:7,0,0,Math.PI*2);c.stroke();c.globalAlpha=.35;c.strokeStyle='#1c2925';c.lineWidth=4;c.beginPath();c.ellipse(x,y+20,elite?34:28,elite?11:9,0,0,Math.PI*2);c.stroke();c.restore()}
function drawEnemies(s,t,now){const area=s.M?.area||'qingyun',matched=match(s.enemies||[],now,area);for(const tr of matched){const e=tr.e;if(e.type==='spirit'){centered('effects',0,4,frame(t,3.2,4),e.x,e.y,48,false,.7);continue}const near=dist(e,s.P)<(e.type==='elite'?70:48);if(near&&now-tr.lastAttack>.72){tr.attackStart=now;tr.lastAttack=now;tr.facing=(s.P?.x??e.x)>=e.x?1:-1}const attacking=now-tr.attackStart<.55,moving=Math.hypot(tr.x-tr.px,tr.y-tr.py)>.15,key=enemyKey(area,e.type);let row=0,idx=moving?frame(t,9,6,tr.id*.09):frame(t,2.15,6,tr.id*.17),h=e.type==='elite'?88:e.type==='rat'?42:e.type==='rogue'?54:e.type==='guard'?66:60;if(attacking){row=1;idx=progress((now-tr.attackStart)/.55,6)}const idle=!moving&&!attacking,roamAmp=e.type==='chaser'?6:e.type==='guard'?3.5:e.type==='elite'?2:2.5,rx=idle?Math.sin(t*.82+tr.id*1.71)*roamAmp:0,ry=idle?Math.sin(t*.57+tr.id*.91)*1.5:0,x=e.x+rx,y=e.y+ry;if(e.rare){const c=S.ctx;c.save();c.globalAlpha=.28;c.strokeStyle=area==='blood'?'#ba493b':'#ad8b43';c.lineWidth=3;c.beginPath();c.arc(x,y,31,0,Math.PI*2);c.stroke();c.restore()}drawEnemyMarker(x,y,h,e.type==='elite',e.rare);const ground=y+22;shadow(x,ground,25,5,.24);const hit=now<tr.hitUntil,filter=hit?'brightness(2.8) saturate(.15) drop-shadow(0 0 3px #fff6d8)':'drop-shadow(0 1px 1px rgba(245,239,215,.72)) drop-shadow(0 0 2px rgba(25,31,28,.72))';anchored(key,row,6,idx,x,ground,h,tr.facing<0,1,'body',filter);const hpRatio=(e.hp||0)/(tr.maxHp||e.hp||1);if(e.type==='elite'||hit||dist(e,s.P)<145)drawBar(x,ground-h-9,e.type==='elite'?52:40,hpRatio,e.type==='elite')}for(let i=deaths.length-1;i>=0;i--){const d=deaths[i],age=now-d.start;if(age>.72){deaths.splice(i,1);continue}const key=enemyKey(d.area||area,d.type),ground=d.y+22,h=d.type==='elite'?88:d.type==='guard'?66:60;shadow(d.x,ground,25,4,.14*(1-age/.72));anchored(key,2,4,progress(age/.72,4),d.x,ground,h,d.facing<0,1-age*.55)}}
function drawPlayer(s,t){const p=s.P;if(!p)return;let moving=false,dx=0;if(prevP){dx=p.x-prevP.x;moving=Math.hypot(dx,p.y-prevP.y)>.16}if(Math.abs(dx)>.12)pFacing=dx<0?-1:1;if(p.tx!==undefined&&Math.abs(p.tx-p.x)>2)pFacing=p.tx<p.x?-1:1;const mortal=(s.M?.realm?.major??-1)<0,atk=s.M?.cult?.atk||1,maxCd=Math.max(.2,.55-(atk-1)*.02),att=!mortal&&p.cd>0.01,attackPhase=att?1-Math.min(maxCd,p.cd)/maxCd:0;let row=0,cols=4,idx=frame(t,4,4);if(att){row=2;cols=6;idx=attackPhase<.36?0:attackPhase<.72?1:0}else if(moving){row=1;cols=6;idx=frame(t,10,6)}const ground=p.y+23;shadow(p.x,ground,11,3,.19);anchored('player',row,cols,idx,p.x,ground,53,pFacing<0);if(att)drawPlayerSlash(p.x,ground,attackPhase,pFacing<0);prevP={x:p.x,y:p.y}}
const effectRow={sword:0,wave:1,chain:2,thunder:3,array:4};
function detectCasts(s,now){const cds=s.run?.skillCooldowns||{};for(const[id,value]of Object.entries(cds)){const before=prevCooldowns[id]??value;if(value>before+.12){let x=s.P?.x||350,y=s.P?.y||230;if(id==='sword')x+=pFacing*48;else if(id==='thunder'&&s.enemies?.length){x=s.enemies[0].x;y=s.enemies[0].y}casts.push({id,x,y,start:now,facing:pFacing})}prevCooldowns[id]=value}}
function drawCasts(now){for(let i=casts.length-1;i>=0;i--){const e=casts[i],age=now-e.start;if(age>.64){casts.splice(i,1);continue}const row=effectRow[e.id];if(row===undefined)continue;const size=e.id==='array'?140:e.id==='wave'?116:e.id==='thunder'?102:86;centered('effects',row,4,progress(age/.64,4),e.x,e.y+8,size,e.facing<0,1-age*.35)}}
function objectKey(o){return `${o.type}:${o.grade??'-'}:${Math.round(o.x)}:${Math.round(o.y)}`}
function detectRewards(s,now){if(s.phase!=='run'||!s.run){prevObjects=(s.objects||[]).map(o=>({...o}));prevRun=s.run?{...s.run}:null;return}const prev=prevRun||s.run,ds=Math.max(0,(s.run.s||0)-(prev.s||0)),dh=[0,1,2].map(i=>Math.max(0,(s.run['h'+i]||0)-(prev['h'+i]||0)));const curKeys=new Set((s.objects||[]).map(objectKey)),gone=prevObjects.filter(o=>!curKeys.has(objectKey(o)));const recentDeath=deaths.length?deaths[deaths.length-1]:null;const takeOrigin=(kind,grade)=>{const ix=gone.findIndex(o=>o.type===kind&&(grade==null||o.grade===grade));if(ix>=0)return gone.splice(ix,1)[0];if(recentDeath)return {x:recentDeath.x,y:recentDeath.y};if(s.vein)return {x:s.vein.x,y:s.vein.y};return {x:s.P?.x||350,y:s.P?.y||230}};if(ds>0){const o=takeOrigin('s');pickups.push({kind:'s',x:o.x,y:o.y,start:now,d:.3,amount:ds});floaters.push({text:`+${ds} 영석`,color:'#9e792f',start:now+.18,d:.8})}for(let g=0;g<3;g++)if(dh[g]>0){const o=takeOrigin('h',g);pickups.push({kind:'h',grade:g,x:o.x,y:o.y,start:now,d:.28,amount:dh[g]});floaters.push({text:`+${dh[g]} ${['하급','중급','상급'][g]} 영초`,color:['#477d53','#397d6b','#76549a'][g],start:now+.16,d:.82})}prevObjects=(s.objects||[]).map(o=>({...o}));prevRun={s:s.run.s||0,h0:s.run.h0||0,h1:s.run.h1||0,h2:s.run.h2||0}}
function drawPickupFx(s,t,now){const c=S.ctx,p=s.P||{x:350,y:230};for(let i=pickups.length-1;i>=0;i--){const q=pickups[i],age=now-q.start,u=Math.max(0,Math.min(1,age/q.d));if(u>=1){pickups.splice(i,1);continue}const ease=1-Math.pow(1-u,3),bend=Math.sin(Math.PI*u)*-18,x=q.x+(p.x-q.x)*ease,y=q.y+(p.y-18-q.y)*ease+bend,alpha=1-u*.25,scale=1-u*.55;if(q.kind==='h'){const row=q.grade||0;anchored('objects',row,4,frame(t,1.5,4),x,y+13,32*scale,false,alpha,String(row))}else{c.save();c.globalAlpha=alpha;c.fillStyle='#d9c06d';c.shadowColor='#f5e7a6';c.shadowBlur=8;c.beginPath();c.arc(x,y,5*scale+2,0,Math.PI*2);c.fill();c.restore()}c.save();c.globalAlpha=.25*(1-u);c.strokeStyle=q.kind==='h'?'#79a982':'#c7a95b';c.lineWidth=2;c.beginPath();c.moveTo(q.x,q.y);c.quadraticCurveTo((q.x+p.x)/2,(q.y+p.y)/2-26,x,y);c.stroke();c.restore()}for(let i=floaters.length-1;i>=0;i--){const f=floaters[i],age=now-f.start;if(age<0)continue;if(age>f.d){floaters.splice(i,1);continue}const u=age/f.d;c.save();c.globalAlpha=Math.min(1,age/.1)*(1-u);c.fillStyle=f.color;c.strokeStyle='rgba(250,246,231,.88)';c.lineWidth=3;c.font='700 15px -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif';c.textAlign='center';const x=p.x,y=p.y-46-u*24;c.strokeText(f.text,x,y);c.fillText(f.text,x,y);c.restore()}}
function drawImpacts(now){const c=S.ctx;for(let i=impacts.length-1;i>=0;i--){const q=impacts[i],age=now-q.start;if(age>.42){impacts.splice(i,1);continue}const u=age/.42;c.save();if(age<.14){const beamU=Math.min(1,age/.1),tx=q.fromX+(q.x-q.fromX)*beamU,ty=q.fromY+(q.y-q.fromY)*beamU;c.globalAlpha=1-age/.16;c.strokeStyle='#f6efd3';c.shadowColor='#fff7d6';c.shadowBlur=9;c.lineWidth=4;c.beginPath();c.moveTo(q.fromX,q.fromY);c.lineTo(tx,ty);c.stroke();c.strokeStyle='#8caea3';c.lineWidth=1.4;c.beginPath();c.moveTo(q.fromX,q.fromY+2);c.lineTo(tx,ty+2);c.stroke()}c.globalAlpha=(1-u)*.9;c.strokeStyle='#fff7df';c.lineWidth=2.5;c.beginPath();c.arc(q.x,q.y,7+u*18,0,Math.PI*2);c.stroke();c.beginPath();c.moveTo(q.x-11-u*6,q.y+8);c.lineTo(q.x+12+u*8,q.y-10);c.moveTo(q.x-7,q.y-12-u*4);c.lineTo(q.x+8,q.y+10+u*5);c.stroke();c.globalAlpha=1-u;c.fillStyle='#8b352d';c.strokeStyle='#f8f1dc';c.lineWidth=3;c.font='800 13px sans-serif';c.textAlign='center';const text=`-${Math.max(1,Math.round(q.damage))}`;c.strokeText(text,q.x,q.y-28-u*18);c.fillText(text,q.x,q.y-28-u*18);c.restore()}}
function resetRunVisuals(){tracks.clear();deaths.length=0;casts.length=0;impacts.length=0;pickups.length=0;floaters.length=0;prevP=null;prevCooldowns={};prevObjects=[];prevRun=null;hitStopUntil=0;lastSnapshot=null}
function draw(ms){requestAnimationFrame(draw);if(!S.ready)return;let s;try{s=window.__xianxiaDebug?.snapshot?.()}catch{}if(!s)return;const c=S.ctx,t=ms/1000,now=performance.now()/1000,area=s.M?.area||'qingyun';if(area!==lastArea||s.phase!==lastPhase)resetRunVisuals();lastArea=area;lastPhase=s.phase;detectRewards(s,now);if(now<hitStopUntil){drawImpacts(now);drawPickupFx(s,t,now);lastSnapshot=s;return}c.clearRect(0,0,W,H);drawBackground(area);drawPortal(t);drawHazards(s);drawObjects(s,t);detectCasts(s,now);drawEnemies(s,t,now);drawCasts(now);drawPlayer(s,t);drawImpacts(now);drawPickupFx(s,t,now);lastSnapshot=s}
async function boot(){try{if(!makeLayer())throw new Error('game canvas not found');const entries=await Promise.all(Object.entries(files).map(async([k,v])=>[k,await load(v)]));S.images=Object.fromEntries(entries);prepare('player',[4,6,6]);for(const area of ['qingyun','blackwind','blood','thunder']){prepare(area+'_guard',[6,6,4]);prepare(area+'_chaser',[6,6,4])}prepare('objects',[4,4,4,6,4]);prepare('effects',[4,4,4,4,4]);S.ready=true;document.documentElement.dataset.inkAssets='11.31.1-ready';console.info('[xianxia] ink runtime 11.31.1 feedback ready');requestAnimationFrame(draw)}catch(e){S.error=String(e?.message||e);document.documentElement.dataset.inkAssets='11.31.1-error';console.warn('[xianxia] ink asset runtime failed',e)}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
