(()=>{
'use strict';
if(window.__xianxiaInkRuntime?.version==='11.31')return;
const W=700,H=460,EXIT={x:350,y:438},BASE='assets/ink_v1/';
const files={
 player:'source/player_core.png',objects:'source/world_objects.png',effects:'source/skill_effects.png',
 qingyun_guard:'source/qingyun_stone_boar.png',qingyun_chaser:'source/qingyun_wind_wolf.png',
 blackwind_guard:'source/blackwind_horned_yak.png',blackwind_chaser:'source/blackwind_ink_panther.png',
 blood_guard:'source/blood_armored_bear.png',blood_chaser:'source/blood_ember_fox.png',
 thunder_guard:'source/thunder_stone_rhino.png',thunder_chaser:'source/thunder_lightning_leopard.png',
 bg_qingyun:'runtime/backgrounds/qingyun.png',bg_blackwind:'runtime/backgrounds/blackwind.png',
 bg_blood:'runtime/backgrounds/blood.png',bg_thunder:'runtime/backgrounds/thunder.png'
};
const S={version:'11.31',ready:false,error:null,images:{},layer:null,ctx:null};
window.__xianxiaInkRuntime=S;
const tracks=new Map(),deaths=[],casts=[];let nextId=1,prevP=null,pFacing=1,prevCooldowns={};
const bounds=new Map(),refs=new Map();
function load(path){return new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>resolve(im);im.onerror=()=>reject(new Error('image failed: '+path));im.src=BASE+path+'?v=11.31'})}
function makeLayer(){const game=document.querySelector('#game'),base=document.querySelector('#cv');if(!game||!base)return false;let c=document.querySelector('#v1131InkLayer');if(!c){c=document.createElement('canvas');c.id='v1131InkLayer';c.width=W;c.height=H;c.setAttribute('aria-hidden','true');base.insertAdjacentElement('afterend',c)}S.layer=c;S.ctx=c.getContext('2d');S.ctx.imageSmoothingEnabled=true;return true}
function frame(t,fps,count,offset=0){return Math.floor((t+offset)*fps)%count}
function progress(p,count){return Math.max(0,Math.min(count-1,Math.floor(Math.max(0,Math.min(.999,p))*count)))}
function cell(img,row,rows,cols,index,x,y,w,h,flip=false,alpha=1){if(!img)return;const sw=img.width/cols,sh=img.height/rows,c=S.ctx;c.save();c.globalAlpha=alpha;c.translate(x,y);if(flip)c.scale(-1,1);c.drawImage(img,index*sw,row*sh,sw,sh,-w/2,-h,w,h);c.restore()}
function median(values){const a=[...values].sort((x,y)=>x-y);return a.length?a[Math.floor(a.length/2)]:1}
function prepare(key,counts){const img=S.images[key],rows=counts.length,c=document.createElement('canvas');c.width=img.width;c.height=img.height;const x=c.getContext('2d',{willReadFrequently:true});x.drawImage(img,0,0);const data=x.getImageData(0,0,c.width,c.height).data,body=[];counts.forEach((cols,row)=>{const rowHeights=[];for(let index=0;index<cols;index++){const x0=Math.floor(index*img.width/cols),x1=Math.floor((index+1)*img.width/cols),y0=Math.floor(row*img.height/rows),y1=Math.floor((row+1)*img.height/rows);let l=x1,t=y1,r=x0,b=y0;for(let py=y0;py<y1;py++)for(let px=x0;px<x1;px++)if(data[(py*img.width+px)*4+3]>28){if(px<l)l=px;if(px>r)r=px;if(py<t)t=py;if(py>b)b=py}if(r<l||b<t){l=x0;r=x1-1;t=y0;b=y1-1}const box={x:l,y:t,w:r-l+1,h:b-t+1};bounds.set(`${key}:${row}:${cols}:${index}`,box);rowHeights.push(box.h);if(row<2)body.push(box.h)}refs.set(`${key}:${row}`,median(rowHeights))});refs.set(`${key}:body`,median(body))}
function boxFor(key,row,cols,index){return bounds.get(`${key}:${row}:${cols}:${index}`)}
function anchored(key,row,cols,index,x,groundY,targetHeight,flip=false,alpha=1,group='body'){const img=S.images[key],b=boxFor(key,row,cols,index);if(!img||!b)return;const scale=targetHeight/(refs.get(`${key}:${group}`)||b.h),dw=b.w*scale,dh=b.h*scale,c=S.ctx;c.save();c.globalAlpha=alpha;c.translate(x,groundY);if(flip)c.scale(-1,1);c.drawImage(img,b.x,b.y,b.w,b.h,-dw/2,-dh,dw,dh);c.restore()}
function centered(key,row,cols,index,x,y,targetHeight,flip=false,alpha=1){const img=S.images[key],b=boxFor(key,row,cols,index);if(!img||!b)return;const scale=targetHeight/(refs.get(`${key}:${row}`)||b.h),dw=b.w*scale,dh=b.h*scale,c=S.ctx;c.save();c.globalAlpha=alpha;c.translate(x,y);if(flip)c.scale(-1,1);c.drawImage(img,b.x,b.y,b.w,b.h,-dw/2,-dh/2,dw,dh);c.restore()}
function shadow(x,y,w,h,a=.16){const c=S.ctx;c.save();c.globalAlpha=a;c.fillStyle='#1b2924';c.beginPath();c.ellipse(x,y,w,h,0,0,Math.PI*2);c.fill();c.restore()}
function dist(a,b){return Math.hypot((a?.x||0)-(b?.x||0),(a?.y||0)-(b?.y||0))}
function match(curr,now,area){const old=[...tracks.values()],used=new Set(),out=[];for(const e of curr){let best=null,bd=e.type==='rat'?45:80;for(const t of old){if(used.has(t.id)||t.type!==e.type)continue;const d=Math.hypot(e.x-t.x,e.y-t.y);if(d<bd){bd=d;best=t}}if(!best){best={id:nextId++,type:e.type,x:e.x,y:e.y,px:e.x,py:e.y,seen:now,facing:1,attackStart:-9,lastAttack:-9,area};tracks.set(best.id,best)}else used.add(best.id);best.px=best.x;best.py=best.y;best.x=e.x;best.y=e.y;best.e=e;best.seen=now;best.area=area;const dx=best.x-best.px;if(Math.abs(dx)>.12)best.facing=dx<0?-1:1;out.push(best)}for(const t of [...tracks.values()]){if(out.includes(t))continue;if(now-t.seen<.2){deaths.push({...t,start:now})}tracks.delete(t.id)}return out}
function drawBackground(area){const c=S.ctx,img=S.images['bg_'+area]||S.images.bg_qingyun;c.globalAlpha=1;c.drawImage(img,0,0,W,H);const wash=c.createLinearGradient(0,0,0,H);wash.addColorStop(0,'rgba(247,243,229,.08)');wash.addColorStop(1,'rgba(20,31,28,.10)');c.fillStyle=wash;c.fillRect(0,0,W,H)}
function drawPortal(t){shadow(EXIT.x,EXIT.y+2,32,6,.18);centered('objects',3,6,frame(t,7,6),EXIT.x,EXIT.y-12,74,false,.9)}
function drawObjects(s,t){for(const o of s.objects||[]){if(o.type==='h'){const row=Math.max(0,Math.min(2,o.grade||0)),ground=o.y+16;shadow(o.x,ground,10,3,.17);anchored('objects',row,4,frame(t,4,4,(o.x+o.y)*.003),o.x,ground,42,false,1,String(row))}else{const ground=o.y+14;shadow(o.x,ground,9,3,.15);anchored('objects',4,4,0,o.x,ground,34,false,1,'4')}}if(s.vein){const ground=s.vein.y+22;shadow(s.vein.x,ground,18,5,.2);anchored('objects',4,4,3,s.vein.x,ground,58,false,1,'4')}}
function drawHazards(s){const c=S.ctx;for(const h of s.hazards||[]){c.save();const p=h.struck?1:1-Math.max(0,h.t)/(h.ttl||1);c.globalAlpha=h.struck?.8:.25+p*.45;c.strokeStyle=h.struck?'#eaf4ff':'#495b82';c.lineWidth=h.struck?4:2;c.setLineDash(h.struck?[]:[6,6]);c.beginPath();c.arc(h.x,h.y,h.r*(.82+p*.18),0,Math.PI*2);c.stroke();if(h.struck){c.beginPath();c.moveTo(h.x-7,h.y-60);c.lineTo(h.x+5,h.y-24);c.lineTo(h.x-3,h.y-24);c.lineTo(h.x+9,h.y);c.stroke()}c.restore()}}
function enemyKey(area,type){if(type==='guard'||type==='elite')return area+'_guard';return area+'_chaser'}
function drawEnemies(s,t,now){const area=s.M?.area||'qingyun',matched=match(s.enemies||[],now,area);for(const tr of matched){const e=tr.e;if(e.type==='spirit'){centered('effects',0,4,frame(t,5,4),e.x,e.y,48,false,.7);continue}const near=dist(e,s.P)<(e.type==='elite'?60:40);if(near&&now-tr.lastAttack>.72){tr.attackStart=now;tr.lastAttack=now;tr.facing=(s.P?.x??e.x)>=e.x?1:-1}const attacking=now-tr.attackStart<.55,moving=Math.hypot(tr.x-tr.px,tr.y-tr.py)>.15,key=enemyKey(area,e.type);let row=0,idx=moving?frame(t,9,6,tr.id*.09):0,h=e.type==='elite'?88:e.type==='rat'?42:e.type==='rogue'?54:e.type==='guard'?66:60;if(attacking){row=1;idx=progress((now-tr.attackStart)/.55,6)}if(e.rare){const c=S.ctx;c.save();c.globalAlpha=.32;c.strokeStyle=area==='blood'?'#ba493b':'#ad8b43';c.lineWidth=3;c.beginPath();c.arc(e.x,e.y,31,0,Math.PI*2);c.stroke();c.restore()}const ground=e.y+22;shadow(e.x,ground,24,5,.2);anchored(key,row,6,idx,e.x,ground,h,tr.facing<0)}for(let i=deaths.length-1;i>=0;i--){const d=deaths[i],age=now-d.start;if(age>.72){deaths.splice(i,1);continue}const key=enemyKey(d.area||area,d.type),ground=d.y+22,h=d.type==='elite'?88:d.type==='guard'?66:60;shadow(d.x,ground,25,4,.14*(1-age/.72));anchored(key,2,4,progress(age/.72,4),d.x,ground,h,d.facing<0,1-age*.55)}}
function drawPlayer(s,t){const p=s.P;if(!p)return;let moving=false,dx=0;if(prevP){dx=p.x-prevP.x;moving=Math.hypot(dx,p.y-prevP.y)>.16}if(Math.abs(dx)>.12)pFacing=dx<0?-1:1;if(p.tx!==undefined&&Math.abs(p.tx-p.x)>2)pFacing=p.tx<p.x?-1:1;const mortal=(s.M?.realm?.major??-1)<0,atk=s.M?.cult?.atk||1,maxCd=Math.max(.2,.55-(atk-1)*.02),att=!mortal&&p.cd>0.01;let row=0,cols=4,idx=frame(t,4,4);if(att){row=2;cols=6;idx=progress(1-Math.min(maxCd,p.cd)/maxCd,6)}else if(moving){row=1;cols=6;idx=frame(t,10,6)}const ground=p.y+23;shadow(p.x,ground,15,4,.19);anchored('player',row,cols,idx,p.x,ground,76,pFacing<0);prevP={x:p.x,y:p.y}}
const effectRow={sword:0,wave:1,chain:2,thunder:3,array:4};
function detectCasts(s,now){const cds=s.run?.skillCooldowns||{};for(const[id,value]of Object.entries(cds)){const before=prevCooldowns[id]??value;if(value>before+.12){let x=s.P?.x||350,y=s.P?.y||230;if(id==='sword'){x+=pFacing*48}else if(id==='thunder'&&s.enemies?.length){x=s.enemies[0].x;y=s.enemies[0].y}casts.push({id,x,y,start:now,facing:pFacing})}prevCooldowns[id]=value}}
function drawCasts(now){for(let i=casts.length-1;i>=0;i--){const e=casts[i],age=now-e.start;if(age>.64){casts.splice(i,1);continue}const row=effectRow[e.id];if(row===undefined)continue;const size=e.id==='array'?140:e.id==='wave'?116:e.id==='thunder'?102:86;centered('effects',row,4,progress(age/.64,4),e.x,e.y+8,size,e.facing<0,1-age*.35)}}
function draw(ms){requestAnimationFrame(draw);if(!S.ready)return;let s;try{s=window.__xianxiaDebug?.snapshot?.()}catch{}if(!s)return;const c=S.ctx,t=ms/1000,now=performance.now()/1000;c.clearRect(0,0,W,H);drawBackground(s.M?.area||'qingyun');drawPortal(t);drawHazards(s);drawObjects(s,t);detectCasts(s,now);drawEnemies(s,t,now);drawCasts(now);drawPlayer(s,t)}
async function boot(){try{if(!makeLayer())throw new Error('game canvas not found');const entries=await Promise.all(Object.entries(files).map(async([k,v])=>[k,await load(v)]));S.images=Object.fromEntries(entries);prepare('player',[4,6,6]);for(const area of ['qingyun','blackwind','blood','thunder']){prepare(area+'_guard',[6,6,4]);prepare(area+'_chaser',[6,6,4])}prepare('objects',[4,4,4,6,4]);prepare('effects',[4,4,4,4,4]);S.ready=true;document.documentElement.dataset.inkAssets='11.31-ready';console.info('[xianxia] ink asset runtime 11.31 ready');requestAnimationFrame(draw)}catch(e){S.error=String(e?.message||e);document.documentElement.dataset.inkAssets='11.31-error';console.warn('[xianxia] ink asset runtime failed',e)}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
