(()=>{
'use strict';

const debug=window.__xianxiaDebug;
if(!debug)return;
const C=debug.constants;
const $=s=>document.querySelector(s);
const HN=['하급','중급','상급'];
const MAJORS=['연기','축기','결단','원영'];
const notice=$('#notice');
const SAVE_KEY='xianxia_proto_v11';
const CENTER_X=550;
let trainCam=null,mapCam=null,selectedTrain={type:'root'},selectedMap={type:'area',area:'qingyun'};
let renderQueued=false,pickerSignature='',savedRunSkills=null;

const T=(id,name,glyph,desc,cost,effect)=>({id,name,glyph,desc,cost,effect});
const K=(s=0,h=0,hg=0)=>({s,h,hg});
const TRAIN=[
 {id:'q1',name:'연기 1층',req:{major:0,stage:1},nodes:[
  T('q1_atk','검결 · 입문','劍','검기의 첫 흐름을 다듬습니다.',K(20),{atk:1}),
  T('q1_hp','체수련 · 기혈','體','기혈을 다져 초반 생존력을 높입니다.',K(0,5,0),{hp:1}),
  T('q1_mov','경신법 · 보법','步','짧은 보법을 익혀 이동을 가볍게 합니다.',K(26),{mov:1}),
  T('q1_sen','신식 · 초감','識','주변 영초와 전리품을 더 멀리 감지합니다.',K(0,5,0),{sen:1})]},
 {id:'q2',name:'연기 2층',req:{major:0,stage:2},nodes:[
  T('q2_atk','검결 · 연격','劍','기본 검격의 연결을 다듬습니다.',K(55),{atk:1}),
  T('q2_hp','체수련 · 호흡','體','호흡과 기혈 순환을 안정시킵니다.',K(0,8,0),{hp:1}),
  T('q2_mov','경신법 · 유보','步','방향 전환과 추격 능력을 높입니다.',K(52),{mov:1}),
  T('q2_sen','신식 · 감응','識','영기 흔적을 더 넓게 읽습니다.',K(0,8,0),{sen:1})]},
 {id:'q3',name:'연기 3층',req:{major:0,stage:3},nodes:[
  T('q3_atk','검결 · 파봉','劍','검결의 힘을 응축해 타격을 강화합니다.',K(88),{atk:1}),
  T('q3_hp','체수련 · 단련','體','근골과 기혈을 한 단계 단련합니다.',K(0,11,0),{hp:1}),
  T('q3_mov','경신법 · 활보','步','비경에서의 이동 손실을 줄입니다.',K(96),{mov:1}),
  T('q3_sen','신식 · 확청','識','전리품 감응 반경을 확장합니다.',K(0,12,0),{sen:1})]},
 {id:'q4',name:'연기 4층',req:{major:0,stage:4},nodes:[
  T('q4_atk','검결 · 심화','劍','중반 검결의 핵심. 검결이 크게 상승합니다.',K(190),{atk:2}),
  T('q4_hp','체수련 · 강근','體','중급 영초로 육신을 강화합니다.',K(0,4,1),{hp:1}),
  T('q4_mov','경신법 · 축지','步','짧은 거리를 빠르게 파고드는 보법입니다.',K(145),{mov:1}),
  T('q4_sen','신식 · 확장','識','중급 영초로 신식을 한 단계 확장합니다.',K(0,4,1),{sen:1})]},
 {id:'q5',name:'연기 5층',req:{major:0,stage:5},nodes:[
  T('q5_atk','검결 · 절맥','劍','검세를 날카롭게 다듬어 검결을 크게 높입니다.',K(290),{atk:2}),
  T('q5_hp','체수련 · 철골','體','육신을 강하게 단련합니다.',K(0,6,1),{hp:2}),
  T('q5_mov','경신법 · 부유','步','상위 비경의 둔화에 대비합니다.',K(300),{mov:1}),
  T('q5_sen','신식 · 투시','識','복잡한 지형에서도 영기 흔적을 읽습니다.',K(0,6,1),{sen:1})]},
 {id:'q6',name:'연기 6층',req:{major:0,stage:6},nodes:[
  T('q6_atk','검결 · 응축','劍','검기를 단단히 응축합니다.',K(470),{atk:1}),
  T('q6_hp','체수련 · 내련','體','내부 기혈 순환을 강화합니다.',K(0,8,1),{hp:1}),
  T('q6_mov','경신법 · 유영','步','경신법이 크게 상승합니다.',K(430),{mov:2}),
  T('q6_sen','신식 · 투영','識','신식이 크게 확장됩니다.',K(0,8,1),{sen:2})]},
 {id:'q7',name:'연기 7층',req:{major:0,stage:7},nodes:[
  T('q7_atk','검결 · 살검','劍','후반 검결의 위력을 끌어올립니다.',K(720),{atk:2}),
  T('q7_hp','체수련 · 옥골','體','상급 영초로 육신을 크게 강화합니다.',K(0,5,2),{hp:2}),
  T('q7_mov','경신법 · 비연','步','위험 지역에서 빠른 이탈이 가능해집니다.',K(760),{mov:1}),
  T('q7_sen','신식 · 심안','識','멀리 떨어진 영기까지 감지합니다.',K(0,5,2),{sen:1})]},
 {id:'q8',name:'연기 8층',req:{major:0,stage:8},nodes:[
  T('q8_atk','검결 · 극의','劍','검결이 크게 상승합니다.',K(1150),{atk:2}),
  T('q8_hp','체수련 · 금근','體','육신의 한계를 한 차례 넘습니다.',K(0,7,2),{hp:2}),
  T('q8_mov','경신법 · 무영','步','경신법이 크게 상승합니다.',K(1000),{mov:2}),
  T('q8_sen','신식 · 외방','識','신식이 크게 확장됩니다.',K(0,7,2),{sen:2})]},
 {id:'q9',name:'연기 9층',req:{major:0,stage:9},nodes:[
  T('q9_atk','검결 · 원만','劍','연기경 검결의 마무리입니다.',K(1650),{atk:3}),
  T('q9_hp','체수련 · 금강','體','연기경 육신의 마무리입니다.',K(0,9,2),{hp:2}),
  T('q9_mov','경신법 · 허공','步','경신법을 극한까지 밀어붙입니다.',K(1500),{mov:2}),
  T('q9_sen','신식 · 원광','識','신식의 범위를 극한까지 확장합니다.',K(0,9,2),{sen:2})]},
 {id:'f1',name:'축기 1층',req:{major:1,stage:1},nodes:[
  T('f1_atk','축기 검결','劍','축기 진원으로 검결을 재정립합니다.',K(2600,6,2),{atk:3}),
  T('f1_hp','축기 육신','體','대경지 돌파에 맞춰 육신을 재구성합니다.',K(0,11,2),{hp:3}),
  T('f1_mov','축기 경신','步','축기 진원으로 경신법을 강화합니다.',K(2600,8,2),{mov:3}),
  T('f1_sen','축기 신식','識','축기 신식으로 감응 범위를 넓힙니다.',K(0,11,2),{sen:3})]}
];
const NODE=Object.fromEntries(TRAIN.flatMap(stage=>stage.nodes.map(node=>[node.id,{...node,stage}])));

const AREA_UNLOCKS={
 blackwind:{s:260,h:18,hg:0,req:{major:0,stage:3},prereq:[['qingyun','eco2',3]],label:'흑풍곡 개방'},
 blood:{s:1350,h:14,hg:1,req:{major:0,stage:6},prereq:[['blackwind','eco2',3],['blackwind','fate2',3]],label:'적혈비경 개방'},
 thunder:{s:4200,h:14,hg:2,req:{major:1,stage:1},prereq:[['blood','eco3',3],['blood','res2',3]],label:'천뢰봉 개방'}
};
const BRANCHES={qingyun:['eco'],blackwind:['eco','fate'],blood:['eco','fate','res'],thunder:['eco','fate','res','storm']};
const AREA_GLYPH={qingyun:'青',blackwind:'風',blood:'血',thunder:'雷'};
const BRANCH_GLYPH={eco:'獸',fate:'緣',res:'脈',storm:'雷'};
const MAP={
 qingyun:{root:{x:200,y:650},region:{x:55,y:510,w:330,h:245},branches:{eco:[{x:260,y:625},{x:315,y:575},{x:355,y:515}]},gate:{blackwind:{x:405,y:470}}},
 blackwind:{root:{x:470,y:385},region:{x:330,y:250,w:330,h:250},branches:{eco:[{x:415,y:345},{x:390,y:300},{x:370,y:255}],fate:[{x:530,y:360},{x:570,y:315},{x:610,y:275}]},gate:{blood:{x:650,y:430}}},
 blood:{root:{x:790,y:560},region:{x:635,y:405,w:350,h:280},branches:{eco:[{x:720,y:610},{x:690,y:655},{x:665,y:700}],fate:[{x:790,y:500},{x:790,y:450},{x:790,y:405}],res:[{x:855,y:585},{x:900,y:610},{x:945,y:635}]},gate:{thunder:{x:930,y:380}}},
 thunder:{root:{x:1010,y:220},region:{x:850,y:70,w:290,h:250},branches:{eco:[{x:930,y:230},{x:900,y:190},{x:880,y:145}],fate:[{x:970,y:165},{x:970,y:120},{x:970,y:85}],res:[{x:1045,y:165},{x:1080,y:125},{x:1110,y:95}],storm:[{x:1060,y:235},{x:1100,y:220},{x:1130,y:195}]}}
};

function snap(){return debug.snapshot()}
function state(){return snap().M}
function clone(v){return JSON.parse(JSON.stringify(v))}
function herbKey(g){return g===0?'herb':g===1?'herb2':'herb3'}
function herbHave(M,g){return Number(M[herbKey(g)])||0}
function reached(M,req){return M.realm?.major>=0&&(M.realm.major>req.major||(M.realm.major===req.major&&M.realm.stage>=req.stage))}
function realmLabel(req){return `${MAJORS[req.major]||'상위경지'} ${req.stage}층`}
function ensure(M){M.trainingNodes||={};M.cult||={atk:1,mov:1,sen:1,hp:1};M.skills||={};return M}
function currentStageIndex(M){let idx=-1;for(let i=0;i<TRAIN.length;i++)if(reached(M,TRAIN[i].req))idx=i;return idx}
function completed(M,stage){return stage?.nodes.filter(n=>M.trainingNodes?.[n.id]).length||0}
function costText(c){return[c.s?`영석 ${c.s}`:'',c.h?`${HN[c.hg]} 영초 ${c.h}`:''].filter(Boolean).join(' · ')||'무료'}
function canBuyTrain(M,node){const shot=snap();if(shot.phase==='run')return[false,'원정 중에는 수련할 수 없습니다.'];if(M.trainingNodes?.[node.id])return[false,'이미 수련 완료'];if(!reached(M,node.stage.req))return[false,`${node.stage.name} 도달 필요`];if((Number(M.stone)||0)<node.cost.s||herbHave(M,node.cost.hg)<node.cost.h)return[false,'수련 재료 부족'];return[true,'수련 가능']}
function applyCult(M,effect){for(const [k,v] of Object.entries(effect))M.cult[k]=(Number(M.cult[k])||0)+v}
function buyTrain(id){const node=NODE[id];if(!node)return;const M=ensure(state()),[ok,why]=canBuyTrain(M,node);if(!ok){notice.textContent=why;return}M.stone-=node.cost.s;if(node.cost.h)M[herbKey(node.cost.hg)]-=node.cost.h;applyCult(M,node.effect);M.trainingNodes[id]=1;debug.replaceState(M);notice.textContent=`${node.stage.name} · ${node.name} 수련 완료.`;scheduleRender()}
function breakthroughCost(targetIdx){if(targetIdx===0)return{s:0,h:8,hg:0,label:'수선 입문'};if(targetIdx===9)return{s:4800,h:75,hg:2,label:'축기 돌파',major:true};return{s:Math.ceil(120*1.62**(targetIdx-1)),h:Math.ceil(16*1.27**(targetIdx-1)),hg:Math.min(2,Math.floor((targetIdx-1)/3)),label:`연기 ${targetIdx+1}층 돌파`}}
function stageStatus(targetIdx){const shot=snap(),M=ensure(shot.M),cur=currentStageIndex(M),target=TRAIN[targetIdx];if(!target)return{can:false,text:'경지 정보 없음'};if(targetIdx<=cur)return{can:false,reached:true,text:targetIdx===cur?'현재 경지':'도달 완료'};if(targetIdx!==cur+1)return{can:false,text:'이전 경지 돌파 필요'};const price=breakthroughCost(targetIdx);if(shot.phase==='run')return{can:false,text:'원정 중에는 돌파할 수 없음',price};if(targetIdx>0){const d=completed(M,TRAIN[targetIdx-1]);if(d<2)return{can:false,text:`${TRAIN[targetIdx-1].name} 수련 ${d}/4 · 2개 이상 필요`,price}}if(price.major&&!M.events?.foundationInsight)return{can:false,text:'축기의 실마리 필요',price};if((Number(M.stone)||0)<price.s||herbHave(M,price.hg)<price.h)return{can:false,text:'돌파 재료 부족',price};return{can:true,text:'돌파 가능',price}}
function breakthrough(targetIdx){const st=TRAIN[targetIdx],s=stageStatus(targetIdx);if(!st||!s.can){notice.textContent=s.text;return}const M=ensure(state()),c=s.price;M.stone-=c.s;if(c.h)M[herbKey(c.hg)]-=c.h;M.realm={...st.req};debug.replaceState(M);notice.textContent=`${st.name} 도달 — 더 넓은 수련 가지가 열렸습니다.`;scheduleRender();requestAnimationFrame(focusTraining)}

function zoneRank(M,area,id){return Math.max(0,Math.min(5,Number(M.zones?.[area]?.tree?.[id])||0))}
function areaIndex(id){return Math.max(0,C.AREAS.findIndex(a=>a.id===id))}
function nodeReq(area,node){const a=C.AREAS.find(x=>x.id===area);return{major:a.req.major,stage:a.baseStage+node.tier-1}}
function affinityCost(M,area,node){const level=zoneRank(M,area,node.id),idx=areaIndex(area),mul=[1,3,8,16][idx]||16,grow=1+level*.7;return{s:Math.ceil(node.c.s*mul*grow),h:Math.ceil(node.c.h*(1+idx*.5)*grow),hg:Math.min(2,idx)}}
function canAffinity(M,area,node){if(snap().phase==='run')return[false,'원정 중에는 강화할 수 없습니다.'];if(!M.unlocked?.[area])return[false,'비경을 먼저 개방해야 합니다.'];const lv=zoneRank(M,area,node.id);if(lv>=5)return[false,'5/5 완성'];const req=nodeReq(area,node);if(!reached(M,req))return[false,`${realmLabel(req)} 필요`];if(node.p&&zoneRank(M,area,node.p)<3)return[false,'선행 지점 3/5 필요'];const c=affinityCost(M,area,node);if(M.stone<c.s||herbHave(M,c.hg)<c.h)return[false,'강화 재료 부족'];return[true,'강화 가능']}
function buyAffinity(area,id){const M=state(),node=Object.values(C.TREE).flat().find(n=>n.id===id);if(!node)return;const [ok,why]=canAffinity(M,area,node);if(!ok){notice.textContent=why;return}const c=affinityCost(M,area,node);M.stone-=c.s;if(c.h)M[herbKey(c.hg)]-=c.h;M.zones[area].tree[id]=zoneRank(M,area,id)+1;debug.replaceState(M);notice.textContent=`${C.AREAS.find(a=>a.id===area).name} · ${node.n} ${M.zones[area].tree[id]}/5 강화.`;scheduleRender()}
function canUnlockArea(M,id){if(M.unlocked?.[id])return[true,'이미 개방됨'];const gate=AREA_UNLOCKS[id];if(!gate)return[false,'기본 비경'];if(!reached(M,gate.req))return[false,`${realmLabel(gate.req)} 필요`];for(const [area,node,rank] of gate.prereq)if(zoneRank(M,area,node)<rank){const def=Object.values(C.TREE).flat().find(n=>n.id===node);return[false,`${C.AREAS.find(a=>a.id===area).name} · ${def?.n||node} ${rank}/5 필요`]}if(M.stone<gate.s||herbHave(M,gate.hg)<gate.h)return[false,'개방 재료 부족'];return[true,'개방 가능']}
function unlockArea(id){const M=state();if(M.unlocked?.[id]){debug.selectArea(id);notice.textContent=`${C.AREAS.find(a=>a.id===id).name}을 원정지로 선택했습니다.`;scheduleRender();return}const [ok,why]=canUnlockArea(M,id);if(!ok){notice.textContent=why;return}const g=AREA_UNLOCKS[id];M.stone-=g.s;M[herbKey(g.hg)]-=g.h;M.unlocked[id]=1;M.area=id;debug.replaceState(M);notice.textContent=`${C.AREAS.find(a=>a.id===id).name} 개방.`;scheduleRender();requestAnimationFrame(focusMap)}

function addCss(){if($('#v1111style'))return;const s=document.createElement('style');s.id='v1111style';s.textContent=`
.tabs.v1111-tabs{grid-template-columns:repeat(3,1fr)}.v1111-hide{display:none!important}
.asc-section{margin-top:0}.asc-viewport,.map-viewport{position:relative;height:clamp(380px,52dvh,560px);overflow:hidden;border:1px solid #31474a;border-radius:12px;touch-action:none;cursor:grab;-webkit-user-select:none;user-select:none}.asc-viewport{background:radial-gradient(circle at 50% 100%,#21423899,#091317 54%,#071014)}.map-viewport{background:linear-gradient(160deg,#1b2019,#111a1c 48%,#17151a)}
.asc-world,.map-world{position:absolute;left:0;top:0;transform-origin:0 0;will-change:transform}.asc-svg,.map-svg{position:absolute;inset:0;width:100%;height:100%;pointer-events:none;overflow:visible}
.asc-line{fill:none;stroke:#405c53;stroke-width:3;opacity:.72}.asc-line.on{stroke:#67b295;filter:drop-shadow(0 0 4px #67b29555)}.asc-line.branch{stroke-width:2}.asc-line.gate{stroke:#a88e50;stroke-dasharray:8 6}
.asc-node{position:absolute;transform:translate(-50%,-50%);margin:0;border:1px solid #43575a;background:#111d22;color:#7e918d;box-shadow:0 5px 15px #0007}.asc-stage{width:68px;height:68px;border-radius:50%;display:grid;place-items:center;text-align:center;padding:5px}.asc-stage b{display:block;font:700 11px serif}.asc-stage small{display:block;font-size:7px;margin-top:2px}.asc-stage.on{border-color:#65ad94;background:#17362e;color:#ddf5eb}.asc-stage.current{outline:2px solid #edf7f2;outline-offset:4px}.asc-stage.available{border-color:#c8aa55;color:#ffe7a3;box-shadow:0 0 20px #d7b95a55}.asc-stage.root{width:82px;height:82px;border-color:#9c8550;background:#302a1b;color:#ffe8a1;box-shadow:0 0 25px #d6b65a42}.asc-leaf{width:54px;height:54px;padding:0;clip-path:polygon(28% 0,72% 0,100% 28%,100% 72%,72% 100%,28% 100%,0 72%,0 28%);display:grid;place-items:center}.asc-leaf .glyph{font:800 21px serif}.asc-leaf .mark{position:absolute;right:2px;bottom:2px;min-width:15px;height:14px;border:1px solid #50636a;border-radius:99px;background:#071014dd;display:grid;place-items:center;font-size:7px}.asc-leaf.ready{border-color:#c8aa55;color:#f4dfa0;box-shadow:0 0 14px #d7b95a44}.asc-leaf.done{border-color:#5fae92;background:#17372f;color:#d4f3e8}.asc-leaf.locked{opacity:.42;filter:saturate(.45)}
.asc-crown{position:absolute;transform:translate(-50%,-50%);border:1px solid #34514944;border-radius:50%;background:radial-gradient(ellipse,#17362c18,transparent 68%);pointer-events:none}.asc-label{position:absolute;transform:translate(-50%,-50%);font-size:8px;color:#647b75;letter-spacing:.12em;pointer-events:none}.camera{position:absolute;z-index:10;right:7px;top:7px;display:flex;gap:3px;padding:3px;border:1px solid #344a4c;border-radius:9px;background:#081216dd}.camera button{width:31px;height:29px;margin:0;padding:0;border:1px solid #3b5153;border-radius:6px;background:#152529}.camera button:nth-child(2){width:44px;font-size:8px}.detail{margin-top:8px;padding:9px;border:1px solid #354c4c;border-radius:10px;background:#0d191d;min-height:88px}.detail-head{display:flex;justify-content:space-between;gap:8px}.detail-head b{font-size:12px}.detail-head span{font-size:9px;color:#9db0ac}.detail p{margin:5px 0;color:#8fa29e;font-size:9px;line-height:1.45}.detail-action{width:100%;min-height:37px;margin-top:7px;border:1px solid #647b67;border-radius:8px;background:#23463b;font-size:10px;font-weight:750}.detail-action.ready{border-color:#b79b4d;background:#4a3e20;color:#fff0bc}
.map-world{width:1200px;height:820px}.map-zone{position:absolute;border:1px solid #66735b44;background:#24302422;pointer-events:none;filter:drop-shadow(0 8px 20px #0005)}.map-zone span{position:absolute;font:700 13px serif;letter-spacing:.14em;color:#9eab8c88;text-shadow:0 1px 3px #000}.map-zone.qingyun{border-radius:48% 35% 55% 40%;transform:rotate(-7deg)}.map-zone.blackwind{border-radius:55% 40% 48% 58%;transform:rotate(8deg);background:#3b332222;border-color:#88764d44}.map-zone.blood{border-radius:42% 58% 44% 55%;transform:rotate(-4deg);background:#47232820;border-color:#8d4d5544}.map-zone.thunder{border-radius:55% 45% 60% 35%;transform:rotate(8deg);background:#252a4928;border-color:#6c75a144}
.map-route{fill:none;stroke:#8c886c;stroke-width:6;stroke-linecap:round;opacity:.38}.map-route.on{stroke:#77ad91;opacity:.72}.map-route.gate{stroke:#c0a55e;stroke-dasharray:11 8;opacity:.65}.map-river{fill:none;stroke:#607d8f55;stroke-width:12;stroke-linecap:round}.map-contour{fill:none;stroke:#b5b38b14;stroke-width:1.4}.map-node{position:absolute;transform:translate(-50%,-50%);margin:0;border:1px solid #4a5550;background:#131b1b;color:#89928c;box-shadow:0 5px 14px #0008}.map-root{width:84px;height:64px;border-radius:46% 54% 50% 44%;padding:5px;text-align:center}.map-root b{display:block;font:700 11px serif}.map-root small{display:block;font-size:7px;margin-top:2px}.map-root.on{border-color:#6aa98d;background:#17342d;color:#dff3e9}.map-root.current{outline:2px solid #f0f3da;outline-offset:4px}.map-point{width:45px;height:45px;border-radius:50%;display:grid;place-items:center;padding:0}.map-point .glyph{font:800 17px serif}.map-point .rank{position:absolute;right:-4px;bottom:-4px;min-width:19px;height:16px;border:1px solid #596762;border-radius:99px;background:#091114;display:grid;place-items:center;font-size:7px}.map-point.on{border-color:#5fae92;background:#17372f;color:#d4f3e8}.map-point.available{border-color:#c5a957;color:#f4dfa0}.map-point.locked{opacity:.44}.map-gate{width:58px;height:42px;border-radius:12px;padding:3px;text-align:center;border-color:#a58c4c;background:#312a1b;color:#dfca8d}.map-gate b{display:block;font:700 10px serif}.map-gate small{display:block;font-size:6px}.map-deco{position:absolute;pointer-events:none;color:#89927844;font:20px serif}.map-compass{position:absolute;right:14px;bottom:12px;width:48px;height:48px;border:1px solid #8f917055;border-radius:50%;display:grid;place-items:center;color:#aeb09088;font:700 10px serif;pointer-events:none}.map-compass:before{content:'N';position:absolute;top:2px}.map-compass:after{content:'↑';font-size:22px;transform:translateY(3px)}
.expedition-area-picker{margin:8px 0 6px;padding:7px;border:1px solid #32474c;border-radius:10px;background:#0c171bcc;text-align:left}.expedition-area-head{display:flex;justify-content:space-between;gap:8px;margin-bottom:5px}.expedition-area-head b{font-size:10px}.expedition-area-head span{font-size:8px;color:#7f9490}.expedition-area-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:4px}.expedition-area-btn{min-height:40px;margin:0;padding:4px 2px;border:1px solid #354b50;border-radius:8px;background:#122026;color:#93a6a2;text-align:center}.expedition-area-btn i{display:block;font:700 15px serif;font-style:normal}.expedition-area-btn span{display:block;font-size:7px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.expedition-area-btn.active{border-color:#63ac96;background:#1b443b;color:#e3f6ef}.expedition-plan-label{margin:5px 0 4px;text-align:left;font-size:9px;color:#869b97}
.dev-milestones{margin-top:10px;padding:8px;border:1px solid #35464a;border-radius:9px;background:#0d171b}.dev-milestones b{display:block;margin-bottom:5px;font-size:10px}.dev-milestone-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:5px}.dev-milestone-grid button{margin:0;min-height:33px;padding:4px;border:1px solid #4d5c60;border-radius:7px;background:#17252a;font-size:8px}
@media(max-width:560px){.asc-viewport,.map-viewport{height:410px}.asc-leaf{width:50px;height:50px}.map-world{width:1200px;height:820px}.expedition-area-btn{min-height:35px}}
`;
document.head.appendChild(s)}

function camera(view,world,w,h){const c={x:0,y:0,s:.6,p:new Map(),g:null},min=.24,max=1.7,apply=()=>world.style.transform=`translate(${c.x}px,${c.y}px) scale(${c.s})`,focus=(x,y,s=.68)=>{const r=view.getBoundingClientRect();if(r.width<40)return;c.s=Math.max(min,Math.min(max,s));c.x=r.width/2-x*c.s;c.y=r.height/2-y*c.s;apply()},fit=()=>{const r=view.getBoundingClientRect();if(r.width<40)return;c.s=Math.max(min,Math.min(.82,(r.width-18)/w,(r.height-18)/h));c.x=(r.width-w*c.s)/2;c.y=(r.height-h*c.s)/2;apply()},zoom=f=>{const r=view.getBoundingClientRect(),cx=r.width/2,cy=r.height/2,wx=(cx-c.x)/c.s,wy=(cy-c.y)/c.s,n=Math.max(min,Math.min(max,c.s*f));c.x=cx-wx*n;c.y=cy-wy*n;c.s=n;apply()},gesture=()=>{const p=[...c.p.values()];if(!p.length)return null;const ctr={x:p.reduce((a,b)=>a+b.x,0)/p.length,y:p.reduce((a,b)=>a+b.y,0)/p.length};return{n:p.length,ctr,d:p.length>1?Math.hypot(p[0].x-p[1].x,p[0].y-p[1].y):0}};view.addEventListener('pointerdown',e=>{if(e.target.closest('button'))return;c.p.set(e.pointerId,{x:e.clientX,y:e.clientY});c.g=gesture()},{passive:false});view.addEventListener('pointermove',e=>{if(!c.p.has(e.pointerId))return;e.preventDefault();const old=c.g;c.p.set(e.pointerId,{x:e.clientX,y:e.clientY});const now=gesture();if(old&&now){const dx=now.ctr.x-old.ctr.x,dy=now.ctr.y-old.ctr.y;if(old.n>1&&now.n>1&&old.d){const r=view.getBoundingClientRect(),os=c.s,ns=Math.max(min,Math.min(max,os*now.d/old.d)),ox=old.ctr.x-r.left,oy=old.ctr.y-r.top,nx=now.ctr.x-r.left,ny=now.ctr.y-r.top,wx=(ox-c.x)/os,wy=(oy-c.y)/os;c.x=nx-wx*ns;c.y=ny-wy*ns;c.s=ns}else{c.x+=dx;c.y+=dy}apply()}c.g=now},{passive:false});const end=e=>{c.p.delete(e.pointerId);c.g=gesture()};view.addEventListener('pointerup',end);view.addEventListener('pointercancel',end);return{focus,fit,zoom}}
function svgPath(svg,a,b,cls='asc-line'){const p=document.createElementNS('http://www.w3.org/2000/svg','path'),mx=(a.y+b.y)/2;p.setAttribute('d',`M ${a.x} ${a.y} C ${a.x} ${mx}, ${b.x} ${mx}, ${b.x} ${b.y}`);p.setAttribute('class',cls);svg.appendChild(p)}
function mapPath(svg,a,b,cls='map-route'){const p=document.createElementNS('http://www.w3.org/2000/svg','path'),mx=(a.x+b.x)/2;p.setAttribute('d',`M ${a.x} ${a.y} C ${mx} ${a.y-35}, ${mx} ${b.y+35}, ${b.x} ${b.y}`);p.setAttribute('class',cls);svg.appendChild(p)}

function setupTabs(){const tabs=$('.tabs');tabs.classList.remove('v12-two');tabs.classList.add('v1111-tabs');const train=$('.tab-btn[data-tab="train"]'),skills=$('.tab-btn[data-tab="skills"]'),areas=$('.tab-btn[data-tab="areas"]'),tree=$('.tab-btn[data-tab="tree"]');train.textContent='수련';skills.textContent='법술';tree.textContent='비경 지도';skills.classList.remove('v12-hide','v1111-hide');$('[data-panel="skills"]')?.classList.remove('v12-hide','v1111-hide');areas.classList.add('v1111-hide');$('[data-panel="areas"]')?.classList.add('v1111-hide');train.parentElement.style.gridTemplateColumns='repeat(3,1fr)';const trainPanel=$('[data-panel="train"]');trainPanel.querySelector('#breakthrough')?.closest('.section')?.classList.add('v1111-hide');trainPanel.querySelector('.train-grid')?.closest('.section')?.classList.add('v1111-hide');trainPanel.querySelector('.asc-section')?.remove();const record=trainPanel.querySelector('.record-grid')?.closest('.section');const sec=document.createElement('div');sec.className='section asc-section';sec.innerHTML=`<div class="section-head"><b>수련 도맥</b><span class="small">범인에서 위로 · 경지가 오를수록 가지가 넓어짐</span></div><div id="ascViewport" class="asc-viewport"><div id="ascWorld" class="asc-world" style="width:1100px;height:1780px"><svg class="asc-svg" viewBox="0 0 1100 1780"></svg></div><div class="camera"><button data-c="out">−</button><button data-c="fit">전체</button><button data-c="in">＋</button></div></div><div id="ascDetail" class="detail"></div>`;trainPanel.insertBefore(sec,record||null);trainCam=camera($('#ascViewport'),$('#ascWorld'),1100,1780);sec.querySelector('[data-c="out"]').onclick=()=>trainCam.zoom(1/1.2);sec.querySelector('[data-c="fit"]').onclick=trainCam.fit;sec.querySelector('[data-c="in"]').onclick=()=>trainCam.zoom(1.2);
 const treePanel=$('[data-panel="tree"]');treePanel.innerHTML=`<div class="section"><div class="section-head"><b>비경 개척 지도</b><span class="small">산길과 관문을 따라 새로운 비경으로</span></div><div id="mapViewport" class="map-viewport"><div id="mapWorld" class="map-world"><svg class="map-svg" viewBox="0 0 1200 820"></svg><div class="map-compass"></div></div><div class="camera"><button data-m="out">−</button><button data-m="fit">전체</button><button data-m="in">＋</button></div></div><div id="mapDetail" class="detail"></div></div>`;mapCam=camera($('#mapViewport'),$('#mapWorld'),1200,820);treePanel.querySelector('[data-m="out"]').onclick=()=>mapCam.zoom(1/1.2);treePanel.querySelector('[data-m="fit"]').onclick=mapCam.fit;treePanel.querySelector('[data-m="in"]').onclick=()=>mapCam.zoom(1.2);
 train.addEventListener('click',()=>requestAnimationFrame(focusTraining));tree.addEventListener('click',()=>requestAnimationFrame(focusMap));}

function ascNode(world,opt,click){const b=document.createElement('button');b.type='button';b.className=`asc-node ${opt.cls||''}`;b.style.left=`${opt.x}px`;b.style.top=`${opt.y}px`;b.innerHTML=opt.html;b.onclick=e=>{e.stopPropagation();click?.()};world.appendChild(b);return b}
function stageY(i){return 1550-i*135}
function renderTraining(){const M=ensure(state()),world=$('#ascWorld');if(!world)return;const svg=world.querySelector('svg');world.querySelectorAll('.asc-node,.asc-crown,.asc-label').forEach(e=>e.remove());svg.innerHTML='';const root={x:CENTER_X,y:1690};const rootCurrent=M.realm.major<0;ascNode(world,{...root,cls:`asc-stage root ${rootCurrent?'current':''}`,html:`<b>凡 · 범인</b><small>모든 길의 시작</small>`},()=>{selectedTrain={type:'root'};renderTrainDetail()});
 TRAIN.forEach((stage,i)=>{const y=stageY(i),open=reached(M,stage.req),current=M.realm.major===stage.req.major&&M.realm.stage===stage.req.stage,status=stageStatus(i),center={x:CENTER_X,y};const prev=i===0?root:{x:CENTER_X,y:stageY(i-1)};svgPath(svg,prev,center,`asc-line ${open?'on':status.can?'gate':''}`);const spread=120+i*30,crown=document.createElement('div');crown.className='asc-crown';crown.style.cssText=`left:${CENTER_X}px;top:${y-34}px;width:${spread*2+170}px;height:${90+i*4}px`;world.appendChild(crown);ascNode(world,{...center,cls:`asc-stage ${open?'on':status.can?'available':'locked'} ${current?'current':''}`,html:`<b>${stage.name}</b><small>${completed(M,stage)}/4</small>`},()=>{selectedTrain={type:'stage',idx:i};renderTrainDetail()});const xs=[CENTER_X-spread,CENTER_X-spread*.38,CENTER_X+spread*.38,CENTER_X+spread],ys=[y-48,y-68,y-68,y-48];stage.nodes.forEach((raw,j)=>{const n=NODE[raw.id],p={x:xs[j],y:ys[j]},done=!!M.trainingNodes?.[n.id],[can]=canBuyTrain(M,n);svgPath(svg,center,p,`asc-line branch ${done?'on':''}`);ascNode(world,{...p,cls:`asc-leaf ${done?'done':can?'ready':'locked'}`,html:`<span class="glyph">${n.glyph}</span><span class="mark">${done?'✓':can?'＋':'·'}</span>`},()=>{selectedTrain={type:'node',id:n.id};renderTrainDetail()})});const label=document.createElement('div');label.className='asc-label';label.style.left=`${CENTER_X}px`;label.style.top=`${y+52}px`;label.textContent=i<9?'↑ 상승':'대경지';world.appendChild(label)});renderTrainDetail()}
function renderTrainDetail(){const M=ensure(state()),box=$('#ascDetail');if(!box)return;if(selectedTrain.type==='root'){const s=stageStatus(0),c=s.price||breakthroughCost(0);box.innerHTML=`<div class="detail-head"><b>凡 · 범인</b><span>시작점</span></div><p>이미 활성화된 뿌리 노드입니다. 영초를 모아 첫 경지인 연기 1층으로 올라갑니다.</p><div>${s.can?'연기 1층 입문 가능':s.text} · 비용 ${costText(c)}</div>`;const b=document.createElement('button');b.className=`detail-action ${s.can?'ready':''}`;b.disabled=!s.can;b.textContent='연기 1층 · 수선 입문';b.onclick=()=>breakthrough(0);box.appendChild(b);return}
 if(selectedTrain.type==='stage'){const idx=selectedTrain.idx,st=TRAIN[idx],cur=currentStageIndex(M),count=completed(M,st);if(idx>cur){const s=stageStatus(idx),c=s.price||breakthroughCost(idx);box.innerHTML=`<div class="detail-head"><b>${st.name}</b><span>경지 관문</span></div><p>${s.text}</p><div>돌파 비용 · ${costText(c)}</div>`;const b=document.createElement('button');b.className=`detail-action ${s.can?'ready':''}`;b.disabled=!s.can;b.textContent=s.can?(idx===0?'수선 입문':`${st.name} 돌파`):'조건 미충족';b.onclick=()=>breakthrough(idx);box.appendChild(b);return}box.innerHTML=`<div class="detail-head"><b>${st.name}</b><span>${idx===cur?'현재 경지':'도달 완료'} · ${count}/4</span></div><p>이 경지의 네 가지 수련은 각각 독립 노드입니다. 위로 올라갈수록 가지가 더 넓게 펼쳐집니다.</p>`;if(idx===cur&&idx+1<TRAIN.length){const s=stageStatus(idx+1),b=document.createElement('button');b.className=`detail-action ${s.can?'ready':''}`;b.disabled=!s.can;b.textContent=s.can?`${TRAIN[idx+1].name} 돌파`:`다음 경지 · ${s.text}`;b.onclick=()=>breakthrough(idx+1);box.appendChild(b)}return}
 const n=NODE[selectedTrain.id]||NODE[TRAIN[0].nodes[0].id],done=!!M.trainingNodes?.[n.id],[can,why]=canBuyTrain(M,n),key=Object.keys(n.effect)[0];box.innerHTML=`<div class="detail-head"><b>${n.stage.name} · ${n.name}</b><span>${done?'수련 완료':'독립 수련'}</span></div><p>${n.desc}</p><div>효과 · ${{atk:'검결',hp:'체수련',mov:'경신법',sen:'신식'}[key]} +${n.effect[key]}<br>${done?'✓ 이미 적용됨':`비용 · ${costText(n.cost)} · ${why}`}</div>`;const b=document.createElement('button');b.className=`detail-action ${can?'ready':''}`;b.disabled=!can;b.textContent=done?'수련 완료':'이 수련 익히기';b.onclick=()=>buyTrain(n.id);box.appendChild(b)}
function focusTraining(){if(!trainCam)return;const M=state(),idx=currentStageIndex(M);if(idx<0)trainCam.focus(CENTER_X,1690,.7);else trainCam.focus(CENTER_X,stageY(idx),.68)}

function region(world,id){const m=MAP[id],a=C.AREAS.find(x=>x.id===id),d=document.createElement('div');d.className=`map-zone ${id}`;d.style.cssText=`left:${m.region.x}px;top:${m.region.y}px;width:${m.region.w}px;height:${m.region.h}px`;d.innerHTML=`<span style="left:18px;top:14px">${a.name}</span>`;world.appendChild(d)}
function mapNode(world,opt,click){const b=document.createElement('button');b.type='button';b.className=`map-node ${opt.cls||''}`;b.style.left=`${opt.x}px`;b.style.top=`${opt.y}px`;b.innerHTML=opt.html;b.onclick=e=>{e.stopPropagation();click?.()};world.appendChild(b);return b}
function renderMap(){const M=state(),world=$('#mapWorld');if(!world)return;const svg=world.querySelector('svg');world.querySelectorAll('.map-zone,.map-node,.map-deco').forEach(e=>e.remove());svg.innerHTML='';const river=document.createElementNS('http://www.w3.org/2000/svg','path');river.setAttribute('d','M 40 160 C 280 240, 360 720, 620 720 S 980 620, 1180 760');river.setAttribute('class','map-river');svg.appendChild(river);for(let i=0;i<7;i++){const p=document.createElementNS('http://www.w3.org/2000/svg','ellipse');p.setAttribute('cx',180+i*150);p.setAttribute('cy',130+(i%3)*210);p.setAttribute('rx',95+i*4);p.setAttribute('ry',55+i*3);p.setAttribute('class','map-contour');svg.appendChild(p)}for(const a of C.AREAS)region(world,a.id);[['▲',120,570],['▲',150,545],['▲',420,300],['▲',440,275],['≈',575,720],['▲',1020,110],['☁',1080,165],['✦',735,455]].forEach(([t,x,y])=>{const d=document.createElement('div');d.className='map-deco';d.style.left=x+'px';d.style.top=y+'px';d.textContent=t;world.appendChild(d)});
 const q=MAP.qingyun.root,bw=MAP.blackwind.root,bl=MAP.blood.root,th=MAP.thunder.root;mapPath(svg,q,MAP.qingyun.gate.blackwind,M.unlocked.blackwind?'map-route on':'map-route gate');mapPath(svg,MAP.qingyun.gate.blackwind,bw,M.unlocked.blackwind?'map-route on':'map-route gate');mapPath(svg,bw,MAP.blackwind.gate.blood,M.unlocked.blood?'map-route on':'map-route gate');mapPath(svg,MAP.blackwind.gate.blood,bl,M.unlocked.blood?'map-route on':'map-route gate');mapPath(svg,bl,MAP.blood.gate.thunder,M.unlocked.thunder?'map-route on':'map-route gate');mapPath(svg,MAP.blood.gate.thunder,th,M.unlocked.thunder?'map-route on':'map-route gate');
 for(const area of C.AREAS){const m=MAP[area.id],unlocked=!!M.unlocked?.[area.id],current=M.area===area.id;mapNode(world,{...m.root,cls:`map-root ${unlocked?'on':'locked'} ${current?'current':''}`,html:`<b>${AREA_GLYPH[area.id]} ${area.name}</b><small>${unlocked?(current?'현재 원정지':'개방됨'):'미개방'}</small>`},()=>{selectedMap={type:'area',area:area.id};renderMapDetail()});for(const branch of BRANCHES[area.id]){const defs=C.TREE[branch],poses=m.branches[branch];defs.forEach((def,i)=>{const p=poses[i],prev=i===0?m.root:poses[i-1],lv=zoneRank(M,area.id,def.id),[can]=canAffinity(M,area.id,def);mapPath(svg,prev,p,lv>0?'map-route on':'map-route');mapNode(world,{...p,cls:`map-point ${lv?'on':can?'available':'locked'}`,html:`<span class="glyph">${BRANCH_GLYPH[branch]}</span><span class="rank">${lv}/5</span>`},()=>{selectedMap={type:'node',area:area.id,id:def.id};renderMapDetail()})})}}
 for(const [from,to] of [['qingyun','blackwind'],['blackwind','blood'],['blood','thunder']]){const p=MAP[from].gate[to],unlocked=!!M.unlocked?.[to],[can]=canUnlockArea(M,to);mapNode(world,{...p,cls:`map-gate ${unlocked?'on':can?'available':'locked'}`,html:`<b>門 ${C.AREAS.find(a=>a.id===to).name.replace(' 후산','')}</b><small>${unlocked?'개방됨':can?'개방 가능':'관문'}</small>`},()=>{selectedMap={type:'unlock',area:to};renderMapDetail()})}renderMapDetail()}
function renderMapDetail(){const M=state(),box=$('#mapDetail'),sel=selectedMap;if(!box||!sel)return;const area=C.AREAS.find(a=>a.id===sel.area);if(sel.type==='area'){const unlocked=!!M.unlocked?.[sel.area],current=M.area===sel.area;box.innerHTML=`<div class="detail-head"><b>${area.name}</b><span>${area.rec}</span></div><p>${area.desc}</p><div>${unlocked?(current?'현재 원정 비경':'개방 완료 · 원정 선택 가능'):'아직 길이 열리지 않았습니다.'}</div>`;if(unlocked&&!current){const b=document.createElement('button');b.className='detail-action ready';b.disabled=snap().phase==='run';b.textContent='이 비경을 원정지로 선택';b.onclick=()=>unlockArea(sel.area);box.appendChild(b)}return}if(sel.type==='unlock'){const g=AREA_UNLOCKS[sel.area],unlocked=!!M.unlocked?.[sel.area],[can,why]=canUnlockArea(M,sel.area);const reqs=g.prereq.map(([a,n,r])=>`${C.AREAS.find(x=>x.id===a).name} · ${Object.values(C.TREE).flat().find(x=>x.id===n)?.n} ${r}/5`).join(' + ');box.innerHTML=`<div class="detail-head"><b>${g.label}</b><span>${realmLabel(g.req)}</span></div><p>길 조건 · ${reqs}<br>개방 재료 · 영석 ${g.s} · ${HN[g.hg]} 영초 ${g.h}</p><div>${unlocked?'✓ 이미 개방됨':why}</div>`;const b=document.createElement('button');b.className=`detail-action ${can?'ready':''}`;b.disabled=snap().phase==='run'||(!unlocked&&!can);b.textContent=unlocked?'비경 선택':'관문 개방';b.onclick=()=>unlockArea(sel.area);box.appendChild(b);return}const def=Object.values(C.TREE).flat().find(n=>n.id===sel.id),lv=zoneRank(M,sel.area,sel.id),c=affinityCost(M,sel.area,def),[can,why]=canAffinity(M,sel.area,def);box.innerHTML=`<div class="detail-head"><b>${area.name} · ${def.n}</b><span>${lv}/5</span></div><p>${def.d}</p><div>${lv>=5?'✓ 지점 완성':`다음 강화 · ${costText(c)} · ${why}`}</div>`;const b=document.createElement('button');b.className=`detail-action ${can?'ready':''}`;b.disabled=!can;b.textContent=lv>=5?'5/5 완성':`${lv+1}/5 개척`;b.onclick=()=>buyAffinity(sel.area,sel.id);box.appendChild(b)}
function focusMap(){if(!mapCam)return;const M=state(),p=MAP[M.area]?.root||MAP.qingyun.root;mapCam.focus(p.x,p.y,.72)}

function areaPicker(){const plans=$('#planChoices');if(!plans)return null;let wrap=$('#expeditionAreaPicker');if(!wrap){wrap=document.createElement('div');wrap.id='expeditionAreaPicker';wrap.className='expedition-area-picker';wrap.innerHTML='<div class="expedition-area-head"><b>원정 비경</b><span>개방한 지역은 언제든 재입장</span></div><div class="expedition-area-grid"></div>';plans.parentNode.insertBefore(wrap,plans);const label=document.createElement('div');label.className='expedition-plan-label';label.textContent='탐색 방법 선택';plans.parentNode.insertBefore(label,plans)}return wrap}
function renderAreaPicker(force=false){const wrap=areaPicker();if(!wrap)return;const shot=snap(),M=shot.M,areas=C.AREAS.filter(a=>M.unlocked?.[a.id]),sig=`${M.area}|${shot.phase}|${areas.map(a=>a.id).join(',')}`;if(!force&&sig===pickerSignature)return;pickerSignature=sig;const grid=wrap.querySelector('.expedition-area-grid');grid.replaceChildren();for(const area of areas){const b=document.createElement('button');b.type='button';b.className='expedition-area-btn'+(M.area===area.id?' active':'');b.disabled=shot.phase==='run';b.innerHTML=`<i>${AREA_GLYPH[area.id]}</i><span>${area.name.replace(' 후산','')}</span>`;b.onclick=()=>{debug.selectArea(area.id);notice.textContent=`${area.name}을 다음 원정지로 선택했습니다.`;pickerSignature='';scheduleRender()};grid.appendChild(b)}}

const BALANCE={sword:{pow:r=>-1.4+r*.5,range:r=>-1.45+r*.5},wave:{pow:r=>-2+r*.5,range:r=>-2.33+r*.5},chain:{pow:r=>-1.8+r*.5,range:r=>-1+r*.35},thunder:{pow:r=>-2.2+r*.5,range:r=>-2+r*.4},array:{pow:r=>-2.2+r*.5,range:r=>-3.7+r*.45}};
function applyRunBalance(){const shot=snap();if(shot.phase==='run'||savedRunSkills)return;const M=shot.M;savedRunSkills=clone(M.skills||{});for(const [id,r] of Object.entries(BALANCE)){if(!M.skills?.[id])continue;const raw=savedRunSkills[id]||{};M.skills[id].pow=r.pow(Number(raw.pow)||0);M.skills[id].range=r.range(Number(raw.range)||0)}debug.replaceState(M);try{const persisted=clone(M);persisted.skills=clone(savedRunSkills);localStorage.setItem(SAVE_KEY,JSON.stringify(persisted))}catch(e){console.warn('balance save guard',e)}}
function restoreRunBalance(){if(!savedRunSkills)return;const shot=snap();if(shot.phase==='run')return;const M=shot.M;M.skills=clone(savedRunSkills);savedRunSkills=null;debug.replaceState(M);scheduleRender()}
function bindRunBalance(){const start=$('#start');if(start&&!start.dataset.v1111Balance){start.dataset.v1111Balance='1';start.addEventListener('click',applyRunBalance,{capture:true})}const ov=$('#ov');if(ov&&!ov.dataset.v1111Balance){ov.dataset.v1111Balance='1';new MutationObserver(()=>requestAnimationFrame(()=>{restoreRunBalance();renderAreaPicker(true)})).observe(ov,{attributes:true,attributeFilter:['class']})}}

const PRESETS={q1:{label:'연기 1층',idx:0,area:'qingyun',unlocked:['qingyun'],stone:180,herbs:[45,0,0]},q3:{label:'연기 3층',idx:2,area:'blackwind',unlocked:['qingyun','blackwind'],stone:1100,herbs:[90,25,0]},q5:{label:'연기 5층',idx:4,area:'blackwind',unlocked:['qingyun','blackwind'],stone:3500,herbs:[130,65,15]},q7:{label:'연기 7층',idx:6,area:'blood',unlocked:['qingyun','blackwind','blood'],stone:11000,herbs:[170,110,60]},q9:{label:'연기 9층',idx:8,area:'blood',unlocked:['qingyun','blackwind','blood'],stone:32000,herbs:[230,180,140],insight:1},f1:{label:'축기 1층',idx:9,area:'thunder',unlocked:['qingyun','blackwind','blood','thunder'],stone:68000,herbs:[300,260,230],insight:1}};
function jumpPreset(id){const p=PRESETS[id];if(!p||snap().phase==='run')return;const M=state();M.realm={...TRAIN[p.idx].req};M.cult={atk:1,mov:1,sen:1,hp:1};M.trainingNodes={};for(let i=0;i<=p.idx;i++)for(const n of TRAIN[i].nodes){M.trainingNodes[n.id]=1;applyCult(M,n.effect)}M.skills=Object.fromEntries(C.SKILLS.map(skill=>[skill.id,{u:0,pow:0,range:0,cycle:0}]));for(const skill of C.SKILLS)if(reached(M,skill.req)){M.skills[skill.id].u=1;M.skills[skill.id].pow=Math.min(2,Math.max(0,p.idx-C.SKILLS.indexOf(skill)*2>2?1:0));}M.unlocked={qingyun:1};for(const a of p.unlocked)M.unlocked[a]=1;M.area=p.area;M.stone=p.stone;M.herb=p.herbs[0];M.herb2=p.herbs[1];M.herb3=p.herbs[2];M.events={...(M.events||{}),foundationInsight:p.insight?1:0};for(const area of C.AREAS){M.zones[area.id]??={tree:{}};M.zones[area.id].tree={}}const set=(a,t)=>Object.assign(M.zones[a].tree,t);set('qingyun',{eco1:Math.min(5,p.idx+1),eco2:p.idx>=2?3:0,eco3:p.idx>=4?2:0});if(p.idx>=2)set('blackwind',{eco1:Math.min(5,p.idx-1),eco2:p.idx>=4?3:1,fate1:Math.min(5,p.idx-1),fate2:p.idx>=5?3:0});if(p.idx>=5)set('blood',{eco1:Math.min(5,p.idx-4),eco2:p.idx>=7?3:1,fate1:Math.min(5,p.idx-5),res1:Math.min(5,p.idx-5),res2:p.idx>=8?3:0});if(p.idx>=9)set('thunder',{eco1:2,fate1:2,res1:2,storm1:2});debug.replaceState(M);notice.textContent=`DEV · ${p.label} 진행 상태로 이동.`;scheduleRender();requestAnimationFrame(()=>{focusTraining();focusMap()})}
function devTools(){const d=$('details.dev');if(!d)return;d.querySelector('.dev-milestones')?.remove();const w=document.createElement('div');w.className='dev-milestones';w.innerHTML='<b>진행도 마일스톤</b><div class="dev-milestone-grid"></div>';const g=w.querySelector('.dev-milestone-grid');for(const [id,p] of Object.entries(PRESETS)){const b=document.createElement('button');b.type='button';b.textContent=p.label;b.onclick=()=>jumpPreset(id);g.appendChild(b)}d.appendChild(w)}

function renderAll(){renderTraining();renderMap();renderAreaPicker();devTools()}
function scheduleRender(){if(renderQueued)return;renderQueued=true;requestAnimationFrame(()=>{renderQueued=false;renderAll()})}
function observe(){for(const el of [$('#realm'),$('#stone'),$('#herb'),$('#area')])if(el)new MutationObserver(scheduleRender).observe(el,{childList:true,characterData:true,subtree:true});window.addEventListener('resize',()=>requestAnimationFrame(()=>{const panel=$('.panel.active')?.dataset.panel;if(panel==='train')focusTraining();else if(panel==='tree')focusMap()}))}

addCss();setupTabs();bindRunBalance();observe();renderAll();requestAnimationFrame(()=>{focusTraining();focusMap()});
window.__xianxiaProgression={version:'11.11',trainingPath:TRAIN,render:renderAll,buyStageTraining:buyTrain,breakthroughStage:breakthrough,buyAffinity,unlockArea,focusStageTraining:focusTraining,focusCurrentRealm:focusMap,jumpMilestone:jumpPreset};
})();
