(()=>{
'use strict';
const D=window.__xianxiaDebug,P=window.__xianxiaProgression;if(!D||!P||window.__xianxiaSystemsVersion==='11.19')return;window.__xianxiaSystemsVersion='11.19';
const $=s=>document.querySelector(s),C=D.constants,clone=v=>JSON.parse(JSON.stringify(v));
function css(){if($('#v1119systems'))return;const s=document.createElement('style');s.id='v1119systems';s.textContent=`
.v19-danger-svg{position:absolute;z-index:6;inset:0;width:100%;height:100%;pointer-events:none;display:none}.v19-danger-svg.show{display:block}.v19-return-line{stroke:#ffe29a;stroke-width:4;stroke-dasharray:11 9;animation:v19dash .65s linear infinite;filter:drop-shadow(0 0 5px #ffbc55)}.v19-exit-ring{fill:#39d9be18;stroke:#ffe09a;stroke-width:5;transform-box:fill-box;transform-origin:center;animation:v19ring .8s ease-in-out infinite alternate;filter:drop-shadow(0 0 8px #66e8cc)}.v19-exit-core{fill:#84f5d6;opacity:.8}.v19-exit-label{fill:#fff0bb;font:800 18px sans-serif;text-anchor:middle;paint-order:stroke;stroke:#071014;stroke-width:4}.v19-danger-banner{position:absolute;z-index:7;left:50%;top:42px;transform:translateX(-50%);display:none;padding:7px 12px;border:1px solid #ffcf78;border-radius:999px;background:#3a1b13e8;color:#ffe6ae;font-size:11px;font-weight:850;box-shadow:0 0 20px #ff8e4966;pointer-events:none;white-space:nowrap}.v19-danger-banner.show{display:block;animation:v19banner .45s ease-in-out 3 alternate}.v19-danger-ret{border-color:#ffd175!important;background:linear-gradient(180deg,#7f3a25,#542417)!important;color:#fff0c0!important;animation:v19ret .55s ease-in-out infinite alternate!important;box-shadow:0 0 0 2px #ffcf7544,0 0 22px #ff9b4d88!important}@keyframes v19dash{to{stroke-dashoffset:-20}}@keyframes v19ring{to{transform:scale(1.22);opacity:.75}}@keyframes v19ret{to{filter:brightness(1.35);transform:translateY(-1px)}}@keyframes v19banner{to{transform:translateX(-50%) scale(1.04)}}
.tabs.v19-four{grid-template-columns:repeat(4,1fr)!important}.v19-ach-tab{position:relative}.v19-ach-tab.ready:after{content:'';position:absolute;right:7px;top:6px;width:6px;height:6px;border-radius:50%;background:#f2d36e;box-shadow:0 0 8px #f2d36e}.v19-journal{display:grid;gap:6px}.v19-journal-intro{padding:8px;border:1px solid #4a4633;border-radius:9px;background:#1b1a13;color:#c8c4a9;font-size:9px;line-height:1.45}.v19-ach{display:grid;grid-template-columns:38px 1fr auto;gap:7px;align-items:center;padding:8px;border:1px solid #34484b;border-radius:10px;background:#101b20}.v19-ach.done{border-color:#75683e;background:#211f16}.v19-ach.claimed{opacity:.65}.v19-ach-glyph{width:36px;height:36px;border:1px solid #52645f;border-radius:50%;display:grid;place-items:center;font:800 16px serif;background:#0b1518;color:#8ca29c}.v19-ach.done .v19-ach-glyph{border-color:#b49b52;color:#f4dda0;background:#332d1b}.v19-ach-main b{display:block;font:700 11px serif;color:#e7efeb}.v19-ach-main span{display:block;margin-top:2px;font-size:8px;color:#91a39f;line-height:1.3}.v19-ach-reward{margin-top:4px;font-size:8px;color:#d8c785}.v19-ach button{min-width:55px;min-height:30px;padding:3px 6px;border:1px solid #52655f;border-radius:7px;background:#17262a;font-size:8px}.v19-ach.done button{border-color:#aa9048;background:#463b1f;color:#ffe7a0}.v19-ach.claimed button{display:none}
@media(max-width:560px){.v19-danger-banner{top:31px;font-size:9px}.v19-ach{grid-template-columns:34px 1fr auto;padding:6px}.v19-ach-glyph{width:32px;height:32px}}
`;document.head.appendChild(s)}
function dangerUi(){const game=$('#game');if(!game||$('#v19DangerSvg'))return;const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.id='v19DangerSvg';svg.classList.add('v19-danger-svg');svg.setAttribute('viewBox','0 0 700 460');svg.setAttribute('preserveAspectRatio','none');svg.innerHTML='<defs><marker id="v19arrow" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0,0 L8,4 L0,8 Z" fill="#ffe29a"/></marker></defs><line id="v19ReturnLine" class="v19-return-line" x1="350" y1="230" x2="350" y2="420" marker-end="url(#v19arrow)"/><circle class="v19-exit-ring" cx="350" cy="438" r="29"/><circle class="v19-exit-core" cx="350" cy="438" r="8"/><text class="v19-exit-label" x="350" y="397">귀환진</text>';game.appendChild(svg);const b=document.createElement('div');b.id='v19DangerBanner';b.className='v19-danger-banner';b.textContent='비경 붕괴 임박 · 귀환진으로 복귀하십시오';game.appendChild(b)}
let wasDanger=false,bannerTimer=0;function dangerRefresh(){dangerUi();const sh=D.snapshot(),game=$('#game'),ret=$('#ret'),svg=$('#v19DangerSvg'),banner=$('#v19DangerBanner');if(!game||!ret||!svg)return;const danger=sh.phase==='run'&&game.classList.contains('danger');ret.classList.toggle('v19-danger-ret',danger);ret.textContent=danger?'↩ 즉시 귀환':'출구로 복귀';svg.classList.toggle('show',danger);if(danger){const p=sh.P||{x:350,y:230},line=$('#v19ReturnLine');line?.setAttribute('x1',Math.max(0,Math.min(700,p.x||350)));line?.setAttribute('y1',Math.max(0,Math.min(460,p.y||230)));if(!wasDanger&&banner){banner.classList.add('show');clearTimeout(bannerTimer);bannerTimer=setTimeout(()=>banner.classList.remove('show'),2300)}}else banner?.classList.remove('show');wasDanger=danger}
const ACH=[
{id:'first_run',g:'步',n:'초입의 발자취',d:'처음으로 비경에 발을 들였다.',r:{s:20},ok:m=>(m.stats?.totalRuns||0)>=1},
{id:'first_safe',g:'歸',n:'생환지인',d:'처음으로 전리품을 지닌 채 무사 귀환했다.',r:{s:30,h:2,hg:0},ok:m=>(m.stats?.totalSafe||0)>=1},
{id:'qi',g:'氣',n:'범골을 벗다',d:'범인의 몸을 벗고 연기경에 입문했다.',r:{s:55},ok:m=>(m.realm?.major??-1)>=0},
{id:'sword',g:'劍',n:'검기 첫 울림',d:'첫 법술 어검술의 전승을 이었다.',r:{s:80,h:2,hg:0},ok:m=>!!m.skillUnlocks?.sword},
{id:'safe5',g:'生',n:'오귀무상',d:'다섯 차례 비경에서 온전히 살아 돌아왔다.',r:{s:140,h:4,hg:0},ok:m=>(m.stats?.totalSafe||0)>=5},
{id:'blackwind',g:'風',n:'흑풍유객',d:'흑풍곡의 관문을 열어 새로운 땅에 닿았다.',r:{s:190,h:4,hg:0},ok:m=>!!m.unlocked?.blackwind},
{id:'kill30',g:'斬',n:'삼십참',d:'요수와 적대자를 누적 서른 번 쓰러뜨렸다.',r:{s:280},ok:m=>(m.stats?.totalKills||0)>=30},
{id:'blood',g:'血',n:'적혈각명',d:'적혈비경에 자신의 행적을 새겼다.',r:{s:520,h:3,hg:1},ok:m=>!!m.unlocked?.blood},
{id:'foundation',g:'基',n:'기해성축',d:'진원을 굳혀 축기경에 올랐다.',r:{s:950,h:2,hg:2},ok:m=>(m.realm?.major??-1)>=1},
{id:'thunder',g:'雷',n:'천뢰문답',d:'천뢰봉의 문을 열고 천뢰와 마주할 자격을 얻었다.',r:{s:1250,h:3,hg:2},ok:m=>!!m.unlocked?.thunder}
];
const herbKey=g=>g===0?'herb':g===1?'herb2':'herb3';function rewardText(r){return[ r.s?`◆ ${r.s}`:'',r.h?`${['초록','파랑','보라'][r.hg]||''} ❧ ${r.h}`:'' ].filter(Boolean).join(' · ')}
function ensureJournalState(m){m.daohang||={};m.daohang.claimed||={};return m}
function claimAch(id){const sh=D.snapshot();if(sh.phase==='run')return;const m=ensureJournalState(clone(sh.M)),a=ACH.find(x=>x.id===id);if(!a||m.daohang.claimed[id]||!a.ok(m))return;if(a.r.s)m.stone=(+m.stone||0)+a.r.s;if(a.r.h)m[herbKey(a.r.hg)]=(+m[herbKey(a.r.hg)]||0)+a.r.h;m.daohang.claimed[id]=Date.now();D.replaceState(m);renderJournal()}
function journalUi(){const tabs=$('.tabs'),treeBtn=$('.tab-btn[data-tab="tree"]');if(!tabs||!treeBtn)return;tabs.classList.add('v19-four');let b=$('.v19-ach-tab');if(!b){b=document.createElement('button');b.className='tab-btn v19-ach-tab';b.dataset.tab='daohang';b.textContent='도행록';treeBtn.after(b);b.addEventListener('click',()=>{document.querySelectorAll('.tab-btn').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#v19JournalPanel')?.classList.add('active');D.setMenuOpen?.(true);renderJournal()});document.querySelectorAll('.tab-btn:not(.v19-ach-tab)').forEach(x=>x.addEventListener('click',()=>$('#v19JournalPanel')?.classList.remove('active')))}let p=$('#v19JournalPanel');if(!p){p=document.createElement('section');p.id='v19JournalPanel';p.className='panel';p.dataset.panel='daohang';p.innerHTML='<div class="section"><div class="section-head"><b>도행록 · 옥간</b><span class="small">행적은 스스로 새겨진다</span></div><div class="v19-journal-intro">문파의 명을 받아 움직이는 것이 아니라, 살아남고 돌파한 행적 자체가 수행이 된다. 이 옥간은 수선자의 중요한 발자취만을 한 번씩 기록한다.</div><div id="v19Journal" class="v19-journal"></div></div>';$('.controls')?.insertBefore(p,$('details.dev'))}}
function renderJournal(){journalUi();const box=$('#v19Journal'),tab=$('.v19-ach-tab');if(!box)return;const m=ensureJournalState(D.snapshot().M);box.replaceChildren();let ready=0;for(const a of ACH){const done=a.ok(m),claimed=!!m.daohang?.claimed?.[a.id];if(done&&!claimed)ready++;const row=document.createElement('div');row.className='v19-ach '+(done?'done ':'')+(claimed?'claimed':'');row.innerHTML=`<div class="v19-ach-glyph">${a.g}</div><div class="v19-ach-main"><b>${a.n}</b><span>${a.d}</span><div class="v19-ach-reward">명각 보상 · ${rewardText(a.r)}</div></div>`;const btn=document.createElement('button');btn.textContent=claimed?'명각 완료':done?'보상 수령':'미달성';btn.disabled=!done||claimed;btn.onclick=()=>claimAch(a.id);row.appendChild(btn);box.appendChild(row)}tab?.classList.toggle('ready',ready>0)}
function boot(){css();dangerUi();journalUi();renderJournal();setInterval(()=>{dangerRefresh();renderJournal()},350)}boot();
})();
