(()=>{
'use strict';
const D=()=>window.__xianxiaDebug,$=s=>document.querySelector(s),H=['하급','중급','상급'];
const state=()=>D().snapshot().M;
function line(svg,a,b,c=''){const e=document.createElementNS('http://www.w3.org/2000/svg','line');for(const [k,v] of Object.entries({x1:a[0],y1:a[1],x2:b[0],y2:b[1]}))e.setAttribute(k,v);e.setAttribute('class','map-line '+c);svg.appendChild(e)}
function node(w,o){const b=document.createElement('button');b.className='map-node '+(o.cls||'');b.style.left=o.x+'px';b.style.top=o.y+'px';b.innerHTML=`<b>${o.title}</b><span>${o.sub||''}</span>${o.cost?`<small>${o.cost}</small>`:''}`;if(o.disabled)b.disabled=true;if(o.on)b.classList.add('on');if(o.ready)b.classList.add('ready');b.onclick=o.click||(()=>{});w.appendChild(b);return b}
const money=q=>`${q.s?`${q.s}석`:''}${q.s&&q.h?' · ':''}${q.h?`${H[q.hg]}초 ${q.h}`:''}`||'무료';
function cam(v,w){if(!v)return;if(!v._treeCam){const c=v._treeCam={x:10,y:10,s:1,d:0,lx:0,ly:0};const ap=()=>{const q=v.querySelector('.map-world');if(q)q.style.transform=`translate(${c.x}px,${c.y}px) scale(${c.s})`};v.addEventListener('wheel',e=>{e.preventDefault();c.s=Math.max(.45,Math.min(1.6,c.s*(e.deltaY<0?1.1:.91)));ap()},{passive:false});v.addEventListener('pointerdown',e=>{if(e.target.closest('.map-node,.map-mini'))return;c.d=1;c.lx=e.clientX;c.ly=e.clientY;v.setPointerCapture?.(e.pointerId)});v.addEventListener('pointermove',e=>{if(!c.d)return;c.x+=e.clientX-c.lx;c.y+=e.clientY-c.ly;c.lx=e.clientX;c.ly=e.clientY;ap()});v.addEventListener('pointerup',()=>c.d=0);v.addEventListener('pointercancel',()=>c.d=0)}const c=v._treeCam;w.style.transform=`translate(${c.x}px,${c.y}px) scale(${c.s})`}
function renderCult(){const root=$('#cultivationMap');if(!root||!D())return;const m=state(),dbg=D(),C=dbg.constants,h=dbg.helpers;root.innerHTML='<div class="map-world cult-world"><svg class="map-svg"></svg></div>';const w=root.firstElementChild,svg=w.querySelector('svg');cam(root,w);const rn=m.realm.major<0?'범인':`${['연기','축기','결단','원영'][m.realm.major]} ${m.realm.stage}층`;node(w,{x:430,y:18,title:rn,sub:m.realm.major<0?'영초 8로 수선 입문':'중앙 · 경지 돌파',cls:'realm-node',ready:true,click:()=>dbg.actions.breakthrough()});const pos=[[70,130],[230,130],[70,270],[230,270]],tr=[['atk','검결'],['mov','경신법'],['sen','신식'],['hp','체수련']];tr.forEach((it,i)=>{const q=h.trainCost(it[0]),lv=m.cult[it[0]],cp=h.cap(),p=pos[i];line(svg,[480,70],[p[0]+65,p[1]],'left');node(w,{x:p[0],y:p[1],title:it[1],sub:`Lv.${lv}/${cp}`,cost:m.realm.major<0?'입문 후':lv>=cp?'경지 상한':money(q),cls:'train-node',ready:m.realm.major>=0&&lv<cp,disabled:m.realm.major<0||lv>=cp,click:()=>dbg.actions.buyTrain(it[0])})});const sx=690,sy=[95,205,315,425,535];C.SKILLS.forEach((sk,i)=>{const st=m.skills[sk.id],open=h.skillOpen(sk),cp=h.skillCap(sk),y=sy[i];line(svg,i?[sx+65,sy[i-1]+70]:[500,70],[sx+65,y],'right');const cost=!st.u?(open?`${sk.unlock.s}석 · ${H[sk.grade]}초 ${sk.unlock.h}`:`${['연기','축기','결단','원영'][sk.req.major]} ${sk.req.stage}층`):`위력 ${st.pow}/${cp} · 범위 ${st.range}/${cp} · 순환 ${st.cycle}/${cp}`;const n=node(w,{x:sx,y,title:sk.n,sub:st.u?'해금됨 · 자동 발동':'법술 해금',cost,cls:'skill-node',on:!!st.u,ready:open&&!st.u,disabled:!open,click:()=>{if(!st.u)dbg.actions.unlockSkill(sk)}});if(st.u){const mini=document.createElement('div');mini.className='map-mini';[['pow','威'],['range','域'],['cycle','循']].forEach(([k,l])=>{const b=document.createElement('button');b.textContent=`${l} ${st[k]}/${cp}`;b.disabled=st[k]>=cp;b.onclick=e=>{e.stopPropagation();dbg.actions.upgradeSkill(sk,k)};mini.appendChild(b)});n.appendChild(mini)}});[['육신·기초 수련',150,82],['법술·전승',730,52]].forEach(([t,x,y])=>{const d=document.createElement('div');d.className='map-label';d.style.left=x+'px';d.style.top=y+'px';d.textContent=t;w.appendChild(d)})}
const AL={qingyun:{x:60,y:160},blackwind:{x:430,y:85},blood:{x:800,y:200},thunder:{x:1170,y:90}},BO={eco:[[20,120],[20,235],[20,350]],fate:[[150,120],[150,235],[150,350]],res:[[280,120],[280,235],[280,350]],storm:[[410,120],[410,235],[410,350]]};
function renderRealm(){const root=$('#realmMap');if(!root||!D())return;const dbg=D(),m=state(),C=dbg.constants,h=dbg.helpers;root.innerHTML='<div class="map-world realm-world"><svg class="map-svg"></svg></div>';const w=root.firstElementChild,svg=w.querySelector('svg');cam(root,w);C.AREAS.forEach((a,ai)=>{const p=AL[a.id],un=!!m.unlocked[a.id],ready=h.areaReady(a),q=h.areaUnlockCost(a);if(ai){const prev=AL[C.AREAS[ai-1].id];line(svg,[prev.x+250,prev.y+45],[p.x,p.y+45],'area-link')}node(w,{x:p.x,y:p.y,title:(m.area===a.id?'▶ ':'')+a.name,sub:a.rec,cost:un?'개방됨':ready?`개방 · ${money(q)}`:h.areaRequirement(a),cls:'area-node',on:un,ready:ready&&!un,disabled:!ready&&!un,click:()=>{if(!un){[...document.querySelectorAll('#areas .area-btn')].find(b=>b.textContent.includes(a.name))?.click()}else dbg.selectArea(a.id);setTimeout(renderAll,0)}});const bs=a.id==='qingyun'?['eco']:a.id==='blackwind'?['eco','fate']:a.id==='blood'?['eco','fate','res']:['eco','fate','res','storm'];bs.forEach(br=>C.TREE[br].forEach((nd,ni)=>{const off=BO[br][ni],x=p.x+off[0],y=p.y+off[1];if(!ni)line(svg,[p.x+125,p.y+90],[x+55,y],'node-link');else{const pr=BO[br][ni-1];line(svg,[p.x+pr[0]+55,p.y+pr[1]+68],[x+55,y],'node-link')}const lv=m.zones[a.id]?.tree?.[nd.id]||0,reqM=a.req.major,reqS=a.baseStage+nd.tier-1,meet=m.realm.major>reqM||(m.realm.major===reqM&&m.realm.stage>=reqS),prev=!nd.p||(m.zones[a.id]?.tree?.[nd.p]||0)>=3,can=un&&meet&&prev&&lv<5,idx=C.AREAS.findIndex(z=>z.id===a.id),grow=1+lv*.7,mul=[1,3,8,16][idx]||16,cost={s:Math.ceil(nd.c.s*mul*grow),h:Math.ceil(nd.c.h*(1+idx*.5)*grow),hg:Math.min(2,idx)};node(w,{x,y,title:nd.n,sub:`${lv}/5`,cost:lv>=5?'완성':can?money(cost):!un?'비경 잠김':!meet?`${['연기','축기','결단','원영'][reqM]} ${reqS}층`:!prev?'선행 3/5':'',cls:'realm-up-node',on:lv>0,ready:can,disabled:!can,click:()=>{if(m.area!==a.id)dbg.selectArea(a.id);setTimeout(()=>{dbg.actions.buyNode(nd);renderAll()},0)}})}));if(ai<C.AREAS.length-1){const np=AL[C.AREAS[ai+1].id];line(svg,[p.x+75,p.y+235],[np.x,np.y+45],'unlock-link')}});const n=document.createElement('div');n.className='map-note';n.textContent='전체 비경 진행도 · 강화 도중 다음 비경이 가지로 열립니다';w.appendChild(n)}
function renderAll(){requestAnimationFrame(()=>{renderCult();renderRealm()})}
const obs=new MutationObserver(()=>{clearTimeout(window.__treeUiTimer);window.__treeUiTimer=setTimeout(renderAll,30)});const st=$('#stone');if(st)obs.observe(st,{childList:true,subtree:true});window.addEventListener('load',renderAll);setTimeout(renderAll,80);
})();