(()=>{
'use strict';
const D=()=>window.__xianxiaDebug,$=s=>document.querySelector(s),H=['하급','중급','상급'];
const state=()=>D().snapshot().M;
function line(svg,a,b,c=''){const e=document.createElementNS('http://www.w3.org/2000/svg','line');for(const [k,v] of Object.entries({x1:a[0],y1:a[1],x2:b[0],y2:b[1]}))e.setAttribute(k,v);e.setAttribute('class','map-line '+c);svg.appendChild(e)}
function node(w,o){const b=document.createElement('button');b.className='map-node '+(o.cls||'');b.style.left=o.x+'px';b.style.top=o.y+'px';b.innerHTML=`<b>${o.title}</b><span>${o.sub||''}</span>${o.cost?`<small>${o.cost}</small>`:''}`;if(o.disabled)b.disabled=true;if(o.on)b.classList.add('on');if(o.ready)b.classList.add('ready');b.onclick=o.click||(()=>{});w.appendChild(b);return b}
const money=q=>`${q.s?`${q.s}석`:''}${q.s&&q.h?' · ':''}${q.h?`${H[q.hg]}초 ${q.h}`:''}`||'무료';
function cam(v,w){if(!v)return;if(!v._treeCam){const c=v._treeCam={x:10,y:10,s:1,d:0,lx:0,ly:0};const ap=()=>{const q=v.querySelector('.map-world');if(q)q.style.transform=`translate(${c.x}px,${c.y}px) scale(${c.s})`};v.addEventListener('wheel',e=>{e.preventDefault();c.s=Math.max(.45,Math.min(1.6,c.s*(e.deltaY<0?1.1:.91)));ap()},{passive:false});v.addEventListener('pointerdown',e=>{if(e.target.closest('.map-node,.map-mini'))return;c.d=1;c.lx=e.clientX;c.ly=e.clientY;v.setPointerCapture?.(e.pointerId)});v.addEventListener('pointermove',e=>{if(!c.d)return;c.x+=e.clientX-c.lx;c.y+=e.clientY-c.ly;c.lx=e.clientX;c.ly=e.clientY;ap()});v.addEventListener('pointerup',()=>c.d=0);v.addEventListener('pointercancel',()=>c.d=0)}const c=v._treeCam;w.style.transform=`translate(${c.x}px,${c.y}px) scale(${c.s})`}
function renderCult(){const root=$('#cultivationMap');if(!root||!D())return;const m=state(),dbg=D(),C=dbg.constants,h=dbg.helpers;root.innerHTML='<div class="map-world cult-world"><svg class="map-svg"></svg></div>';const w=root.firstElementChild,svg=w.querySelector('svg');cam(root,w);const rn=m.realm.major<0?'凡':(['炼','筑','丹','婴'][m.realm.major]||'境')+m.realm.stage;const core=node(w,{x:435,y:245,title:rn,sub:m.realm.major<0?'입문':'돌파',cls:'realm-node sigil realm-core',ready:true,click:()=>dbg.actions.breakthrough()});core.dataset.tip=m.realm.major<0?'수선 입문 · 하급 영초 8':'현재 경지 · 눌러 돌파';const pos=[[100,105],[85,245],[100,385],[245,470]],tr=[['atk','剑','검결'],['mov','身','경신'],['sen','识','신식'],['hp','体','체수련']];tr.forEach((it,i)=>{const q=h.trainCost(it[0]),lv=m.cult[it[0]],cp=h.cap(),p=pos[i];line(svg,[500,280],[p[0]+35,p[1]+35],'left');const n=node(w,{x:p[0],y:p[1],title:it[1],sub:lv+'/'+cp,cls:'sigil train-node',ready:m.realm.major>=0&&lv<cp,disabled:m.realm.major<0||lv>=cp,click:()=>dbg.actions.buyTrain(it[0])});n.dataset.tip=it[2]+' · '+(m.realm.major<0?'입문 후':lv>=cp?'현재 경지 상한':money(q))});const sp=[[735,80],[840,195],[825,350],[720,465],[555,535]];C.SKILLS.forEach((sk,i)=>{const st=m.skills[sk.id],open=h.skillOpen(sk),cp=h.skillCap(sk),p=sp[i],from=i?[sp[i-1][0]+35,sp[i-1][1]+35]:[505,280];line(svg,from,[p[0]+35,p[1]+35],'right');const glyph=['剑','風','連','雷','陣'][i],n=node(w,{x:p[0],y:p[1],title:glyph,sub:st.u?Math.max(st.pow,st.range,st.cycle)+'/'+cp:'',cls:'sigil skill-node',on:!!st.u,ready:open&&!st.u,disabled:!open,click:()=>{if(!st.u)dbg.actions.unlockSkill(sk)}});n.dataset.tip=sk.n+' · '+(st.u?'해금됨':open?'해금 '+sk.unlock.s+'석 / '+H[sk.grade]+'초 '+sk.unlock.h:'잠김 · '+['연기','축기','결단','원영'][sk.req.major]+' '+sk.req.stage+'층');if(st.u){const mini=document.createElement('div');mini.className='map-mini radial-mini';[['pow','威'],['range','域'],['cycle','循']].forEach(([k,l])=>{const bt=document.createElement('button');bt.textContent=l;bt.title=k+' '+st[k]+'/'+cp;bt.disabled=st[k]>=cp;bt.onclick=e=>{e.stopPropagation();dbg.actions.upgradeSkill(sk,k)};mini.appendChild(bt)});n.appendChild(mini)}});[['근본',145,55],['법술',790,35]].forEach(([t,x,y])=>{const d=document.createElement('div');d.className='map-label brush-label';d.style.left=x+'px';d.style.top=y+'px';d.textContent=t;w.appendChild(d)})}
const AL={qingyun:{x:60,y:160},blackwind:{x:430,y:85},blood:{x:800,y:200},thunder:{x:1170,y:90}},BO={eco:[[20,120],[20,235],[20,350]],fate:[[150,120],[150,235],[150,350]],res:[[280,120],[280,235],[280,350]],storm:[[410,120],[410,235],[410,350]]};
function renderRealm(){const root=$('#realmMap');if(!root||!D())return;const dbg=D(),m=state(),C=dbg.constants,h=dbg.helpers;root.innerHTML='<div class="map-world realm-world"><svg class="map-svg"></svg></div>';const w=root.firstElementChild,svg=w.querySelector('svg');cam(root,w);C.AREAS.forEach((a,ai)=>{const p=AL[a.id],un=!!m.unlocked[a.id],ready=h.areaReady(a),q=h.areaUnlockCost(a);if(ai){const prev=AL[C.AREAS[ai-1].id];line(svg,[prev.x+80,prev.y+50],[p.x+80,p.y+50],'area-link')}const an=node(w,{x:p.x,y:p.y,title:['青','黑','血','雷'][ai],sub:'',cls:'area-node seal-node',on:un,ready:ready&&!un,disabled:!ready&&!un,click:()=>{if(!un){[...document.querySelectorAll('#areas .area-btn')].find(b=>b.textContent.includes(a.name))?.click()}else dbg.selectArea(a.id);setTimeout(renderAll,0)}});an.dataset.tip=a.name+' · '+(un?'개방됨':ready?'개방 '+money(q):h.areaRequirement(a));const bs=a.id==='qingyun'?['eco']:a.id==='blackwind'?['eco','fate']:a.id==='blood'?['eco','fate','res']:['eco','fate','res','storm'];let seq=0;bs.forEach(br=>C.TREE[br].forEach((nd,ni)=>{const ang=(-1.15+seq*.43)+(ai%2?-.12:.12),rad=135+ni*88+(Math.floor(seq/3)*22),x=p.x+65+Math.cos(ang)*rad,y=p.y+45+Math.sin(ang)*rad;line(svg,[p.x+65,p.y+45],[x+27,y+27],'node-link');const lv=m.zones[a.id]?.tree?.[nd.id]||0,reqM=a.req.major,reqS=a.baseStage+nd.tier-1,meet=m.realm.major>reqM||(m.realm.major===reqM&&m.realm.stage>=reqS),prev=!nd.p||(m.zones[a.id]?.tree?.[nd.p]||0)>=3,can=un&&meet&&prev&&lv<5,idx=C.AREAS.findIndex(z=>z.id===a.id),grow=1+lv*.7,mul=[1,3,8,16][idx]||16,cost={s:Math.ceil(nd.c.s*mul*grow),h:Math.ceil(nd.c.h*(1+idx*.5)*grow),hg:Math.min(2,idx)},n=node(w,{x,y,title:['獣','群','異','客','宝','霊','脈','守','巨','雷','避','凝'][seq%12],sub:lv?String(lv):'',cls:'sigil realm-up-node',on:lv>0,ready:can,disabled:!can,click:()=>{if(m.area!==a.id)dbg.selectArea(a.id);setTimeout(()=>{dbg.actions.buyNode(nd);renderAll()},0)}});n.dataset.tip=nd.n+' '+lv+'/5 · '+(lv>=5?'완성':can?money(cost):!un?'비경 잠김':!meet?['연기','축기','결단','원영'][reqM]+' '+reqS+'층':'선행 필요');seq++}));if(ai<C.AREAS.length-1){const np=AL[C.AREAS[ai+1].id],ux=(p.x+np.x)/2+45,uy=(p.y+np.y)/2-15,u=node(w,{x:ux,y:uy,title:'開',sub:'',cls:'unlock-gate sigil',ready:!!m.unlocked[C.AREAS[ai+1].id]||h.areaReady(C.AREAS[ai+1]),disabled:!m.unlocked[C.AREAS[ai+1].id]&&!h.areaReady(C.AREAS[ai+1])});u.dataset.tip=C.AREAS[ai+1].name+' 개방 관문'}})}
function renderAll(){requestAnimationFrame(()=>{renderCult();renderRealm()})}
const obs=new MutationObserver(()=>{clearTimeout(window.__treeUiTimer);window.__treeUiTimer=setTimeout(renderAll,30)});const st=$('#stone');if(st)obs.observe(st,{childList:true,subtree:true});window.addEventListener('load',renderAll);setTimeout(renderAll,80);
})();