const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const {execFileSync}=require('node:child_process');
const root=path.resolve(__dirname,'..');
const manifest=JSON.parse(fs.readFileSync(path.join(root,'assets/ink_v1/manifest.json'),'utf8'));
assert.equal(manifest.version,'1.0.0');
assert.equal(manifest.arena_camera,'three-quarter top-down orthographic');
assert.match(manifest.anchor_policy,/bottom-center ground anchor/);
assert.deepEqual(Object.keys(manifest.backgrounds),['qingyun','blackwind','blood','thunder']);
assert.equal(Object.keys(manifest.sprites).filter(k=>/_guard$|_chaser$/.test(k)).length,8);
const files=[];
files.push(manifest.background_source);
for(const rel of Object.values(manifest.backgrounds))files.push(rel);
for(const value of Object.values(manifest.sprites))files.push(value.file);
for(const rel of Object.values(manifest.ui))files.push(rel);
for(const rel of files){const file=path.join(root,'assets/ink_v1',rel);assert.ok(fs.existsSync(file),`missing ${rel}`);assert.ok(fs.statSync(file).size>1024,`empty ${rel}`)}
const html=fs.readFileSync(path.join(root,'index.html'),'utf8');
assert.match(html,/ink_assets_v11_31\.css/);
assert.match(html,/ink_runtime_v11_31\.js/);
assert.doesNotMatch(html,/sprite_runtime_v11_30\.js/);
const runtime=fs.readFileSync(path.join(root,'ink_runtime_v11_31.js'),'utf8');
const game=fs.readFileSync(path.join(root,'game_v11.js'),'utf8');
assert.match(runtime,/prepare\('player'/);
assert.match(runtime,/anchored\('player'/);
assert.match(runtime,/function spansFor/);
assert.match(runtime,/function largestOpaqueBox/);
assert.doesNotMatch(runtime,/isolated=beast\|\|key==='player'/);
assert.match(runtime,/document\.currentScript/);
assert.match(runtime,/anchored\('player',[^\n]+,53,/);
assert.match(runtime,/function drawPlayerSlash/);
assert.match(runtime,/attackPhase<\.36\?0:attackPhase<\.72\?1:0/);
assert.doesNotMatch(runtime,/beast\?b\.h/);
assert.match(runtime,/function resetRunVisuals/);
assert.match(game,/PLAYER_GROUND_OFFSET=23/);
assert.match(game,/exitDistance<EXIT\.r\+9/);
const visual=fs.readFileSync(path.join(root,'visual_v11_25.js'),'utf8');
assert.doesNotMatch(visual,/v25-tab-glyph/);
const progression=fs.readFileSync(path.join(root,'progression_v11_17.js'),'utf8');
const ui=fs.readFileSync(path.join(root,'ui_v11_17.js'),'utf8');
const systems19=fs.readFileSync(path.join(root,'systems_v11_19.js'),'utf8');
const systems20=fs.readFileSync(path.join(root,'systems_v11_20.js'),'utf8');
const systems22=fs.readFileSync(path.join(root,'systems_v11_22.js'),'utf8');
assert.match(game,/function setMenuOpen/);
assert.match(systems22,/xianxia:panel-open/);
assert.match(systems22,/v22-expedition-mode/);
assert.match(systems22,/grid-template-columns:repeat\(5,1fr\)/);
assert.match(systems22,/document\.body\.appendChild\(tabs\)/);
assert.match(systems22,/function enterCombat/);
assert.match(systems22,/v22-combat-mode/);
assert.match(systems22,/MutationObserver\(\(\)=>\{if\(!ov\.classList\.contains\('hide'\)\)leaveCombat/);
assert.match(systems22,/display:flex!important;flex-direction:column!important/);
assert.match(systems22,/#ascViewport,body\.v22-panel-mode #mapViewport,body\.v22-panel-mode #skillTreeViewport\{flex:1 1 auto!important/);
assert.match(systems22,/data-c=\"fit\"/);
assert.match(systems22,/v22-expedition-mode:not\(\.v22-combat-mode\) \.game canvas/);
assert.match(systems22,/\.controls \.panel\{display:none!important;height:100%!important/);
assert.match(systems22,/ignoreTabsUntil=Date\.now\(\)\+450/);
assert.match(game,/enemy:2\.05,reward:4/);
assert.match(game,/enemy:3\.9,reward:10/);
assert.match(game,/enemy:6\.5,reward:24/);
assert.match(ui,/setupAreaTitlePicker/);
assert.match(ui,/function renderResultAreas/);
assert.match(ui,/D\.selectArea\(a\.id\);syncDialog\(\)/);
assert.match(ui,/start\.textContent='입장'/);
assert.doesNotMatch(ui,/같은 설정으로 다시 진입/);
assert.match(progression,/M\.stone>=sword\.unlock\.s&&herbHave\(M,sword\.grade\)>=sword\.unlock\.h/);
assert.match(ui,/\.map-gate\[data-area=/);
assert.doesNotMatch(systems19,/\.controls'\)\?\.classList\.remove\('open'/);
assert.match(systems20,/const wanted='입장'/);
assert.doesNotMatch(html,/ASSET_CACHE_TOKEN/);
execFileSync(process.execPath,[path.join(root,'scripts/stamp_asset_cache.cjs'),'--check'],{stdio:'pipe'});
console.log(`ink v11.31 assets: ${files.length} files and runtime entrypoints verified`);
